/* SPDX-License-Identifier: GPL-2.0-only */

#include <mainboard/gpio.h>
#include <soc/gpio.h>

/* Pad configuration was generated automatically using intelp2m utility */
static const struct pad_config gpio_table[] = {

	/* ------- GPIO Community 0 ------- */

	/* ------- GPIO Group GPP_B ------- */

	/* GPP_B0 - CORE_VID0 */
	PAD_CFG_NF(GPP_B0, NONE, DEEP, NF1),

	/* GPP_B1 - CORE_VID1 */
	PAD_CFG_NF(GPP_B1, NONE, DEEP, NF1),

	/* GPP_B2 - GPIO */
	PAD_CFG_GPO(GPP_B2, 0, DEEP),

	/* GPP_B3 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_B3, NONE, DEEP, OFF, ACPI),

	/* GPP_B4 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_B4, NONE, DEEP, OFF, ACPI),

	/* GPP_B5 - I2C2_SDA */
	PAD_CFG_NF(GPP_B5, NONE, DEEP, NF2),

	/* GPP_B6 - I2C2_SCL */
	PAD_CFG_NF(GPP_B6, NONE, DEEP, NF2),

	/* GPP_B7 - GPIO */
	PAD_CFG_GPO(GPP_B7, 0, DEEP),

	/* GPP_B8 - GPIO */
	PAD_NC(GPP_B8, NONE),

	/* GPP_B9 - GPIO */
	PAD_CFG_GPO(GPP_B9, 0, DEEP),

	/* GPP_B10 - GPIO */
	PAD_NC(GPP_B10, NONE),

	/* GPP_B11 - PMCALERT# */
	PAD_CFG_NF(GPP_B11, NONE, RSMRST, NF1),

	/* GPP_B12 - SLP_S0# */
	PAD_CFG_NF(GPP_B12, NONE, DEEP, NF1),

	/* GPP_B13 - PLTRST# */
	PAD_CFG_NF(GPP_B13, NONE, DEEP, NF1),

	/* GPP_B14 - SPKR */
	PAD_CFG_NF(GPP_B14, NONE, DEEP, NF1),

	/* GPP_B15 - GPIO */
	PAD_CFG_GPO(GPP_B15, 0, DEEP),

	/* GPP_B16 - GPIO */
	PAD_CFG_GPO(GPP_B16, 0, DEEP),

	/* GPP_B17 - GPIO */
	PAD_NC(GPP_B17, NONE),

	/* GPP_B18 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_B18, NONE, DEEP, OFF, ACPI),

	/* GPP_B19 - GPIO */
	PAD_CFG_GPO(GPP_B19, 0, DEEP),

	/* GPP_B20 - GPIO */
	PAD_CFG_GPO(GPP_B20, 0, DEEP),

	/* GPP_B21 - GPIO */
	PAD_CFG_GPO(GPP_B21, 0, DEEP),

	/* GPP_B22 - GPIO */
	PAD_NC(GPP_B22, NONE),

	/* GPP_B23 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_B23, NONE, DEEP, OFF, ACPI),

	/* GPP_B24 - GSPI0_CLK_LOOPBK */
	PAD_CFG_NF(GPP_B24, NONE, DEEP, NF1),

	/* GPP_B25 - GSPI1_CLK_LOOPBK */
	PAD_CFG_NF(GPP_B25, NONE, DEEP, NF1),

	/* ------- GPIO Group GPP_T ------- */

	/* GPP_T0 - GPIO */
	PAD_NC(GPP_T0, NONE),

	/* GPP_T1 - GPIO */
	PAD_NC(GPP_T1, NONE),

	/* GPP_T2 - GPIO */
	PAD_CFG_GPO(GPP_T2, 0, DEEP),

	/* GPP_T3 - GPIO */
	PAD_NC(GPP_T3, NONE),

	/* GPP_T4 - GPIO */
	PAD_NC(GPP_T4, NONE),

	/* GPP_T5 - GPIO */
	PAD_NC(GPP_T5, NONE),

	/* GPP_T6 - GPIO */
	PAD_NC(GPP_T6, NONE),

	/* GPP_T7 - GPIO */
	PAD_NC(GPP_T7, NONE),

	/* GPP_T8 - GPIO */
	PAD_NC(GPP_T8, NONE),

	/* GPP_T9 - GPIO */
	PAD_NC(GPP_T9, NONE),

	/* GPP_T10 - GPIO */
	PAD_NC(GPP_T10, NONE),

	/* GPP_T11 - GPIO */
	PAD_NC(GPP_T11, NONE),

	/* GPP_T12 - GPIO */
	PAD_NC(GPP_T12, NONE),

	/* GPP_T13 - GPIO */
	PAD_NC(GPP_T13, NONE),

	/* GPP_T14 - GPIO */
	PAD_NC(GPP_T14, NONE),

	/* GPP_T15 - GPIO */
	PAD_NC(GPP_T15, NONE),

	/* ------- GPIO Group GPP_A ------- */

	/* GPP_A0 - ESPI_IO0 */
	PAD_CFG_NF(GPP_A0, UP_20K, DEEP, NF1),

	/* GPP_A1 - ESPI_IO1 */
	PAD_CFG_NF(GPP_A1, UP_20K, DEEP, NF1),

	/* GPP_A2 - ESPI_IO2 */
	PAD_CFG_NF(GPP_A2, UP_20K, DEEP, NF1),

	/* GPP_A3 - ESPI_IO3 */
	PAD_CFG_NF(GPP_A3, UP_20K, DEEP, NF1),

	/* GPP_A4 - ESPI_CS0# */
	PAD_CFG_NF(GPP_A4, UP_20K, DEEP, NF1),

	/* GPP_A5 - ESPI_ALERT0# */
	PAD_CFG_NF(GPP_A5, UP_20K, DEEP, NF1),

	/* GPP_A6 - GPIO */
	PAD_CFG_GPO(GPP_A6, 0, DEEP),

	/* GPP_A7 - GPIO */
	PAD_CFG_GPO(GPP_A7, 0, DEEP),

	/* GPP_A8 - GPIO */
	PAD_NC(GPP_A8, NONE),

	/* GPP_A9 - ESPI_CLK */
	PAD_CFG_NF(GPP_A9, DN_20K, DEEP, NF1),

	/* GPP_A10 - ESPI_RESET# */
	PAD_CFG_NF(GPP_A10, NONE, DEEP, NF1),

	/* GPP_A11 - GPIO */
	PAD_NC(GPP_A11, NONE),

	/* GPP_A12 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_A12, NONE, DEEP, OFF, ACPI),

	/* GPP_A13 - GPIO */
	PAD_CFG_GPO(GPP_A13, 1, PLTRST),

	/* GPP_A14 - GPIO */
	PAD_CFG_GPO(GPP_A14, 1, DEEP),

	/* GPP_A15 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_A15, NONE, DEEP, OFF, ACPI),

	/* GPP_A16 - USB_OC3# */
	PAD_NC(GPP_A16, NONE),

	/* GPP_A17 - GPIO */
	PAD_CFG_GPI_INT(GPP_A17, NONE, PLTRST, LEVEL),

	/* GPP_A18 - DDSP_HPDB */
	PAD_CFG_NF(GPP_A18, NONE, DEEP, NF1),

	/* GPP_A19 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_A19, NONE, DEEP, OFF, ACPI),

	/* GPP_A20 - GPIO */
	PAD_NC(GPP_A20, NONE),

	/* GPP_A21 - GPIO */
	PAD_NC(GPP_A21, NONE),

	/* GPP_A22 - GPIO */
	PAD_CFG_GPO(GPP_A22, 1, PLTRST),

	/* GPP_A23 - GPIO */
	PAD_NC(GPP_A23, NONE),

	/* GPP_ESPI_CLK_LOOPBK - GPP_ESPI_CLK_LOOPBK */
	PAD_CFG_NF(GPP_ESPI_CLK_LOOPBK, NONE, DEEP, NF1),

	/* ------- GPIO Community 1 ------- */

	/* ------- GPIO Group GPP_S ------- */

	/* GPP_S0 - GPIO */
	PAD_CFG_GPO(GPP_S0, 0, DEEP),

	/* GPP_S1 - GPIO */
	PAD_CFG_GPO(GPP_S1, 0, DEEP),

	/* GPP_S2 - GPIO */
	PAD_CFG_GPO(GPP_S2, 0, DEEP),

	/* GPP_S3 - GPIO */
	PAD_CFG_GPO(GPP_S3, 0, DEEP),

	/* GPP_S4 - GPIO */
	PAD_CFG_GPO(GPP_S4, 0, DEEP),

	/* GPP_S5 - GPIO */
	PAD_CFG_GPO(GPP_S5, 0, DEEP),

	/* GPP_S6 - GPIO */
	PAD_CFG_GPO(GPP_S6, 0, DEEP),

	/* GPP_S7 - GPIO */
	PAD_NC(GPP_S7, NONE),

	/* ------- GPIO Group GPP_H ------- */

	/* GPP_H0 - GPIO */
	PAD_CFG_GPO(GPP_H0, 1, PLTRST),

	/* GPP_H1 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_H1, NONE, DEEP, OFF, ACPI),

	/* GPP_H2 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_H2, NONE, DEEP, OFF, ACPI),

	/* GPP_H3 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_H3, NONE, DEEP, OFF, ACPI),

	/* GPP_H4 - I2C0_SDA */
	PAD_CFG_NF(GPP_H4, NONE, DEEP, NF1),

	/* GPP_H5 - I2C0_SCL */
	PAD_CFG_NF(GPP_H5, NONE, DEEP, NF1),

	/* GPP_H6 - I2C1_SDA */
	PAD_CFG_NF(GPP_H6, NONE, DEEP, NF1),

	/* GPP_H7 - I2C1_SCL */
	PAD_CFG_NF(GPP_H7, NONE, DEEP, NF1),

	/* GPP_H8 - CNV_MFUART2_RXD */
	PAD_CFG_NF(GPP_H8, NONE, DEEP, NF2),

	/* GPP_H9 - CNV_MFUART2_TXD */
	PAD_CFG_NF(GPP_H9, NONE, DEEP, NF2),

	/* GPP_H10 - UART0_RXD */
	PAD_CFG_NF(GPP_H10, NONE, DEEP, NF2),

	/* GPP_H11 - UART0_TXD */
	PAD_CFG_NF(GPP_H11, NONE, DEEP, NF2),

	/* GPP_H12 - GPIO */
	PAD_CFG_GPO(GPP_H12, 0, DEEP),

	/* GPP_H13 - GPIO */
	PAD_NC(GPP_H13, NONE),

	/* GPP_H14 - GPIO */
	PAD_NC(GPP_H14, NONE),

	/* GPP_H15 - DDPB_CTRLCLK */
	PAD_CFG_NF(GPP_H15, NONE, DEEP, NF1),

	/* GPP_H16 - GPIO */
	PAD_NC(GPP_H16, NONE),

	/* GPP_H17 - DDPB_CTRLDATA */
	PAD_CFG_NF(GPP_H17, NONE, DEEP, NF1),

	/* GPP_H18 - PROC_C10_GATE# */
	PAD_CFG_NF(GPP_H18, NONE, DEEP, NF1),

	/* GPP_H19 - GPIO */
	PAD_NC(GPP_H19, NONE),

	/* GPP_H20 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_H20, NONE, DEEP, OFF, ACPI),

	/* GPP_H21 - GPIO */
	PAD_CFG_GPO(GPP_H21, 0, DEEP),

	/* GPP_H22 - GPIO */
	PAD_NC(GPP_H22, NONE),

	/* GPP_H23 - SRCCLKREQ5# */
	PAD_CFG_NF(GPP_H23, NONE, DEEP, NF2),

	/* ------- GPIO Group GPP_D ------- */

	/* GPP_D0 - GPIO */
	PAD_CFG_GPO(GPP_D0, 1, DEEP),

	/* GPP_D1 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_D1, NONE, DEEP, OFF, ACPI),

	/* GPP_D2 - GPIO */
	PAD_CFG_GPO(GPP_D2, 1, DEEP),

	/* GPP_D3 - GPIO */
	PAD_CFG_GPO(GPP_D3, 0, DEEP),

	/* GPP_D4 - GPIO */
	PAD_NC(GPP_D4, NONE),

	/* GPP_D5 - SRCCLKREQ0# */
	PAD_CFG_NF(GPP_D5, NONE, DEEP, NF1),

	/* GPP_D6 - GPIO */
	PAD_NC(GPP_D6, NONE),

	/* GPP_D7 - SRCCLKREQ2# */
	PAD_CFG_NF(GPP_D7, NONE, DEEP, NF1),

	/* GPP_D8 - SRCCLKREQ3# */
	PAD_CFG_NF(GPP_D8, NONE, DEEP, NF1),

	/* GPP_D9 - GPIO */
	PAD_NC(GPP_D9, NONE),

	/* GPP_D10 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_D10, NATIVE, DEEP, OFF, ACPI),

	/* GPP_D11 - GPIO */
	PAD_NC(GPP_D11, NONE),

	/* GPP_D12 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_D12, NATIVE, DEEP, OFF, ACPI),

	/* GPP_D13 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_D13, NONE, DEEP, OFF, ACPI),

	/* GPP_D14 - GPIO */
	PAD_CFG_GPO(GPP_D14, 1, PLTRST),

	/* GPP_D15 - GPIO */
	PAD_CFG_GPO(GPP_D15, 0, DEEP),

	/* GPP_D16 - GPIO */
	PAD_NC(GPP_D16, NONE),

	/* GPP_D17 - GPIO */
	PAD_CFG_GPO(GPP_D17, 0, DEEP),

	/* GPP_D18 - GPIO */
	PAD_NC(GPP_D18, NONE),

	/* GPP_D19 - GPIO */
	PAD_NC(GPP_D19, NONE),

	/* GPP_GSPI2_CLK_LOOPBK - GPP_GSPI2_CLK_LOOPBK */
	PAD_CFG_NF(GPP_GSPI2_CLK_LOOPBK, NONE, DEEP, NF1),

	/* ------- GPIO Group RESERVED ------- */

	/* GPP_CPU_RSVD_1 - GPIO */
	PAD_NC(GPP_CPU_RSVD_1, NONE),

	/* GPP_CPU_RSVD_2 - GPIO */
	PAD_NC(GPP_CPU_RSVD_2, NONE),

	/* GPP_CPU_RSVD_3 - GPIO */
	PAD_NC(GPP_CPU_RSVD_3, NONE),

	/* GPP_CPU_RSVD_4 - GPIO */
	PAD_NC(GPP_CPU_RSVD_4, NONE),

	/* GPP_CPU_RSVD_5 - GPIO */
	PAD_NC(GPP_CPU_RSVD_5, NONE),

	/* GPP_CPU_RSVD_6 - GPIO */
	PAD_NC(GPP_CPU_RSVD_6, NONE),

	/* GPP_CPU_RSVD_7 - GPIO */
	PAD_NC(GPP_CPU_RSVD_7, NONE),

	/* GPP_CPU_RSVD_8 - GPIO */
	PAD_NC(GPP_CPU_RSVD_8, NONE),

	/* GPP_CPU_RSVD_9 - GPIO */
	PAD_NC(GPP_CPU_RSVD_9, NONE),

	/* GPP_CPU_RSVD_10 - GPIO */
	PAD_NC(GPP_CPU_RSVD_10, NONE),

	/* GPP_CPU_RSVD_11 - GPIO */
	PAD_NC(GPP_CPU_RSVD_11, NONE),

	/* GPP_CPU_RSVD_12 - GPIO */
	PAD_NC(GPP_CPU_RSVD_12, NONE),

	/* GPP_CPU_RSVD_13 - GPIO */
	PAD_NC(GPP_CPU_RSVD_13, NONE),

	/* GPP_CPU_RSVD_14 - GPIO */
	PAD_NC(GPP_CPU_RSVD_14, NONE),

	/* GPP_CPU_RSVD_15 - GPIO */
	PAD_NC(GPP_CPU_RSVD_15, NONE),

	/* GPP_CPU_RSVD_16 - GPIO */
	PAD_NC(GPP_CPU_RSVD_16, NONE),

	/* GPP_CPU_RSVD_17 - GPIO */
	PAD_NC(GPP_CPU_RSVD_17, NONE),

	/* GPP_CPU_RSVD_18 - GPIO */
	PAD_NC(GPP_CPU_RSVD_18, NONE),

	/* GPP_CPU_RSVD_19 - GPIO */
	PAD_NC(GPP_CPU_RSVD_19, NONE),

	/* GPP_CPU_RSVD_20 - GPIO */
	PAD_NC(GPP_CPU_RSVD_20, NONE),

	/* GPP_CPU_RSVD_21 - GPP_CPU_RSVD_21 */
	PAD_CFG_NF(GPP_CPU_RSVD_21, NONE, DEEP, NF1),

	/* GPP_CPU_RSVD_22 - GPP_CPU_RSVD_22 */
	PAD_CFG_NF(GPP_CPU_RSVD_22, NONE, DEEP, NF1),

	/* GPP_CPU_RSVD_23 - GPP_CPU_RSVD_23 */
	PAD_CFG_NF(GPP_CPU_RSVD_23, NONE, DEEP, NF1),

	/* GPP_CPU_RSVD_24 - GPP_CPU_RSVD_24 */
	PAD_CFG_NF(GPP_CPU_RSVD_24, NONE, DEEP, NF1),

	/* ------- GPIO Group vGPIO ------- */

	/* GPP_VGPIO_0 - GPIO */
	PAD_CFG_GPO(GPP_VGPIO_0, 0, DEEP),

	/* GPP_VGPIO_4 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_VGPIO_4, NONE, DEEP, OFF, ACPI),

	/* GPP_VGPIO_5 - GPIO */
	PAD_CFG_GPIO_BIDIRECT(GPP_VGPIO_5, 1, NONE, DEEP, LEVEL, ACPI),

	/* GPP_VGPIO_6 - GPP_VGPIO_6 */
	PAD_CFG_NF(GPP_VGPIO_6, NONE, DEEP, NF1),

	/* GPP_VGPIO_7 - GPP_VGPIO_7 */
	PAD_CFG_NF(GPP_VGPIO_7, NONE, DEEP, NF1),

	/* GPP_VGPIO_8 - GPP_VGPIO_8 */
	PAD_CFG_NF(GPP_VGPIO_8, NONE, DEEP, NF1),

	/* GPP_VGPIO_9 - GPP_VGPIO_9 */
	PAD_CFG_NF(GPP_VGPIO_9, NONE, DEEP, NF1),

	/* GPP_VGPIO_10 - GPP_VGPIO_10 */
	PAD_CFG_NF(GPP_VGPIO_10, NONE, DEEP, NF1),

	/* GPP_VGPIO_11 - GPP_VGPIO_11 */
	PAD_CFG_NF(GPP_VGPIO_11, NONE, DEEP, NF1),

	/* GPP_VGPIO_12 - GPP_VGPIO_12 */
	PAD_CFG_NF(GPP_VGPIO_12, NONE, DEEP, NF1),

	/* GPP_VGPIO_13 - GPP_VGPIO_13 */
	PAD_CFG_NF(GPP_VGPIO_13, NONE, DEEP, NF1),

	/* GPP_VGPIO_18 - GPP_VGPIO_18 */
	PAD_CFG_NF(GPP_VGPIO_18, NONE, DEEP, NF1),

	/* GPP_VGPIO_19 - GPP_VGPIO_19 */
	PAD_CFG_NF(GPP_VGPIO_19, NONE, DEEP, NF1),

	/* GPP_VGPIO_20 - GPP_VGPIO_20 */
	PAD_CFG_NF(GPP_VGPIO_20, NONE, DEEP, NF1),

	/* GPP_VGPIO_21 - GPP_VGPIO_21 */
	PAD_CFG_NF(GPP_VGPIO_21, NONE, DEEP, NF1),

	/* GPP_VGPIO_22 - GPP_VGPIO_22 */
	PAD_CFG_NF(GPP_VGPIO_22, NONE, DEEP, NF1),

	/* GPP_VGPIO_23 - GPP_VGPIO_23 */
	PAD_CFG_NF(GPP_VGPIO_23, NONE, DEEP, NF1),

	/* GPP_VGPIO_24 - GPP_VGPIO_24 */
	PAD_CFG_NF(GPP_VGPIO_24, NONE, DEEP, NF1),

	/* GPP_VGPIO_25 - GPP_VGPIO_25 */
	PAD_CFG_NF(GPP_VGPIO_25, NONE, DEEP, NF1),

	/* GPP_VGPIO_30 - GPP_VGPIO_30 */
	PAD_CFG_NF(GPP_VGPIO_30, NONE, DEEP, NF1),

	/* GPP_VGPIO_31 - GPP_VGPIO_31 */
	PAD_CFG_NF(GPP_VGPIO_31, NONE, DEEP, NF1),

	/* GPP_VGPIO_32 - GPP_VGPIO_32 */
	PAD_CFG_NF(GPP_VGPIO_32, NONE, DEEP, NF1),

	/* GPP_VGPIO_33 - GPP_VGPIO_33 */
	PAD_CFG_NF(GPP_VGPIO_33, NONE, DEEP, NF1),

	/* GPP_VGPIO_34 - GPP_VGPIO_34 */
	PAD_CFG_NF(GPP_VGPIO_34, NONE, DEEP, NF1),

	/* GPP_VGPIO_35 - GPP_VGPIO_35 */
	PAD_CFG_NF(GPP_VGPIO_35, NONE, DEEP, NF1),

	/* GPP_VGPIO_36 - GPP_VGPIO_36 */
	PAD_CFG_NF(GPP_VGPIO_36, NONE, DEEP, NF1),

	/* GPP_VGPIO_37 - GPP_VGPIO_37 */
	PAD_CFG_NF(GPP_VGPIO_37, NONE, DEEP, NF1),

	/* ------- GPIO Community 2 ------- */

	/* ------- GPIO Group GPP_GPD ------- */

	/* GPD0 - BATLOW# */
	PAD_CFG_NF(GPD0, UP_20K, PWROK, NF1),

	/* GPD1 - ACPRESENT */
	PAD_CFG_NF(GPD1, NATIVE, PWROK, NF1),

	/* GPD2 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPD2, NATIVE, PWROK, OFF, ACPI),

	/* GPD3 - PWRBTN# */
	PAD_CFG_NF(GPD3, UP_20K, PWROK, NF1),

	/* GPD4 - SLP_S3# */
	PAD_CFG_NF(GPD4, NONE, PWROK, NF1),

	/* GPD5 - SLP_S4# */
	PAD_CFG_NF(GPD5, NONE, PWROK, NF1),

	/* GPD6 - SLP_A# */
	PAD_CFG_NF(GPD6, NONE, PWROK, NF1),

	/* GPD7 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPD7, NONE, PWROK, OFF, ACPI),

	/* GPD8 - SUSCLK */
	PAD_CFG_NF(GPD8, NONE, PWROK, NF1),

	/* GPD9 - SLP_WLAN# */
	PAD_CFG_NF(GPD9, NONE, DEEP, NF1),

	/* GPD10 - SLP_S5# */
	PAD_CFG_NF(GPD10, NONE, PWROK, NF1),

	/* GPD11 - LANPHYPC */
	PAD_CFG_NF(GPD11, NONE, PWROK, NF1),

	/* GPD_INPUT3VSEL - GPD_INPUT3VSEL */
	PAD_CFG_NF(GPD_INPUT3VSEL, NONE, PWROK, NF1),

	/* GPD_SLP_LANB - GPD_SLP_LANB */
	PAD_CFG_NF(GPD_SLP_LANB, NONE, PWROK, NF1),

	/* GPD_SLP_SUSB - GPD_SLP_SUSB */
	PAD_CFG_NF(GPD_SLP_SUSB, NONE, PWROK, NF1),

	/* GPD_WAKEB - GPD_WAKEB */
	PAD_CFG_NF(GPD_WAKEB, NONE, PWROK, NF1),

	/* GPD_DRAM_RESETB - GPD_DRAM_RESETB */
	PAD_CFG_NF(GPD_DRAM_RESETB, NONE, PWROK, NF1),

	/* ------- GPIO Group PCIe vGPIO ------- */

	/* ------- GPIO Community 4 ------- */

	/* ------- GPIO Group GPP_C ------- */

	/* GPP_C0 - SMBCLK */
	PAD_CFG_NF(GPP_C0, NONE, DEEP, NF1),

	/* GPP_C1 - SMBDATA */
	PAD_CFG_NF(GPP_C1, NONE, DEEP, NF1),

	/* GPP_C2 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_C2, NONE, DEEP, OFF, ACPI),

	/* GPP_C3 - SML0CLK */
	PAD_CFG_NF(GPP_C3, NONE, DEEP, NF1),

	/* GPP_C4 - SML0DATA */
	PAD_CFG_NF(GPP_C4, NONE, DEEP, NF1),

	/* GPP_C5 - GPIO */
	PAD_CFG_GPO(GPP_C5, 1, PLTRST),

	/* GPP_C6 - SML1CLK */
	PAD_CFG_NF(GPP_C6, NONE, DEEP, NF1),

	/* GPP_C7 - SML1DATA */
	PAD_CFG_NF(GPP_C7, NONE, DEEP, NF1),

	/* GPP_C8 - GPIO */
	PAD_NC(GPP_C8, NONE),

	/* GPP_C9 - GPIO */
	PAD_NC(GPP_C9, NONE),

	/* GPP_C10 - GPIO */
	PAD_NC(GPP_C10, NONE),

	/* GPP_C11 - GPIO */
	PAD_NC(GPP_C11, NONE),

	/* GPP_C12 - GPIO */
	PAD_NC(GPP_C12, NONE),

	/* GPP_C13 - GPIO */
	PAD_NC(GPP_C13, NONE),

	/* GPP_C14 - GPIO */
	PAD_NC(GPP_C14, NONE),

	/* GPP_C15 - GPIO */
	PAD_NC(GPP_C15, NONE),

	/* GPP_C16 - GPIO */
	PAD_NC(GPP_C16, NONE),

	/* GPP_C17 - GPIO */
	PAD_NC(GPP_C17, NONE),

	/* GPP_C18 - GPIO */
	PAD_NC(GPP_C18, NONE),

	/* GPP_C19 - GPIO */
	PAD_NC(GPP_C19, NONE),

	/* GPP_C20 - GPIO */
	PAD_NC(GPP_C20, NONE),

	/* GPP_C21 - GPIO */
	PAD_NC(GPP_C21, NONE),

	/* GPP_C22 - GPIO */
	PAD_NC(GPP_C22, NONE),

	/* GPP_C23 - GPIO */
	PAD_NC(GPP_C23, NONE),

	/* ------- GPIO Group GPP_F ------- */

	/* GPP_F0 - CNV_BRI_DT */
	PAD_CFG_NF(GPP_F0, NONE, DEEP, NF1),

	/* GPP_F1 - CNV_BRI_RSP */
	PAD_CFG_NF(GPP_F1, UP_20K, DEEP, NF1),

	/* GPP_F2 - CNV_RGI_DT */
	PAD_CFG_NF(GPP_F2, NONE, DEEP, NF1),

	/* GPP_F3 - CNV_RGI_RSP */
	PAD_CFG_NF(GPP_F3, UP_20K, DEEP, NF1),

	/* GPP_F4 - CNV_RF_RESET# */
	PAD_CFG_NF(GPP_F4, NONE, DEEP, NF1),

	/* GPP_F5 - CRF_XTAL_CLKREQ */
	PAD_CFG_NF(GPP_F5, NONE, DEEP, NF3),

	/* GPP_F6 - CNV_PA_BLANKING */
	PAD_CFG_NF(GPP_F6, NONE, DEEP, NF1),

	/* GPP_F7 - GPIO */
	PAD_CFG_GPO(GPP_F7, 1, PLTRST),

	/* GPP_F8 - GPIO */
	PAD_NC(GPP_F8, NONE),

	/* GPP_F9 - GPIO */
	PAD_NC(GPP_F9, NONE),

	/* GPP_F10 - GPIO */
	PAD_CFG_GPO(GPP_F10, 1, PLTRST),

	/* GPP_F11 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_F11, NONE, DEEP, OFF, ACPI),

	/* GPP_F12 - GPIO */
	PAD_CFG_GPO(GPP_F12, 1, DEEP),

	/* GPP_F13 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_F13, NONE, PLTRST, OFF, ACPI),

	/* GPP_F14 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_F14, NONE, DEEP, OFF, ACPI),

	/* GPP_F15 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_F15, NONE, DEEP, OFF, ACPI),

	/* GPP_F16 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_F16, NONE, DEEP, OFF, ACPI),

	/* GPP_F17 - GPIO */
	PAD_CFG_GPO(GPP_F17, 1, PLTRST),

	/* GPP_F18 - GPIO */
	PAD_CFG_GPO(GPP_F18, 0, DEEP),

	/* GPP_F19 - SRCCLKREQ6# */
	PAD_CFG_NF(GPP_F19, NONE, DEEP, NF1),

	/* GPP_F20 - GPIO */
	PAD_CFG_GPO(GPP_F20, 1, PLTRST),

	/* GPP_F21 - GPIO */
	PAD_CFG_GPO(GPP_F21, 0, DEEP),

	/* GPP_F22 - GPIO */
	PAD_CFG_GPO(GPP_F22, 0, DEEP),

	/* GPP_F23 - GPIO */
	PAD_NC(GPP_F23, NONE),

	/* GPP_F_CLK_LOOPBK - GPIO */
	PAD_NC(GPP_F_CLK_LOOPBK, NONE),

	/* ------- GPIO Group GPP_HVCMOS ------- */

	/* GPP_L_BKLTEN - n/a */
	PAD_CFG_NF(GPP_L_BKLTEN, NONE, DEEP, NF1),

	/* GPP_L_BKLTCTL - n/a */
	PAD_CFG_NF(GPP_L_BKLTCTL, NONE, DEEP, NF1),

	/* GPP_L_VDDEN - n/a */
	PAD_CFG_NF(GPP_L_VDDEN, NONE, DEEP, NF1),

	/* GPP_SYS_PWROK - n/a */
	PAD_CFG_NF(GPP_SYS_PWROK, NONE, DEEP, NF1),

	/* GPP_SYS_RESETB - n/a */
	PAD_CFG_NF(GPP_SYS_RESETB, NONE, DEEP, NF1),

	/* GPP_MLK_RSTB - n/a */
	PAD_CFG_NF(GPP_MLK_RSTB, NONE, DEEP, NF1),

	/* ------- GPIO Group GPP_E ------- */

	/* GPP_E0 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_E0, NONE, DEEP, OFF, ACPI),

	/* GPP_E1 - GPIO */
	PAD_CFG_GPI_APIC(GPP_E1, UP_20K, DEEP, LEVEL, NONE),

	/* GPP_E2 - GPIO */
	PAD_NC(GPP_E2, NONE),

	/* GPP_E3 - GPIO */
	PAD_CFG_GPO(GPP_E3, 1, DEEP),

	/* GPP_E4 - GPIO */
	PAD_CFG_GPO(GPP_E4, 0, PLTRST),

	/* GPP_E5 - GPIO */
	PAD_NC(GPP_E5, NONE),

	/* GPP_E6 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_E6, NONE, DEEP, OFF, ACPI),

	/* GPP_E7 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_E7, NONE, DEEP, OFF, ACPI),

	/* GPP_E8 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_E8, NONE, DEEP, OFF, ACPI),

	/* GPP_E9 - USB_OC0# */
	PAD_NC(GPP_E9, NONE),

	/* GPP_E10 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_E10, NONE, DEEP, OFF, ACPI),

	/* GPP_E11 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_E11, NONE, DEEP, OFF, ACPI),

	/* GPP_E12 - GPIO */
	PAD_NC(GPP_E12, NONE),

	/* GPP_E13 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_E13, NONE, DEEP, OFF, ACPI),

	/* GPP_E14 - DDSP_HPDA */
	PAD_CFG_NF(GPP_E14, NONE, DEEP, NF1),

	/* GPP_E15 - GPIO */
	PAD_CFG_GPO(GPP_E15, 0, DEEP),

	/* GPP_E16 - GPIO */
	PAD_NC(GPP_E16, NONE),

	/* GPP_E17 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_E17, NONE, DEEP, OFF, ACPI),

	/* GPP_E18 - TBT_LSX0_TXD */
	//PAD_NC(GPP_E18, NATIVE),

	/* GPP_E19 - TBT_LSX0_RXD */
	//PAD_NC(GPP_E19, NATIVE),

	/* GPP_E20 - GPIO */
	PAD_NC(GPP_E20, NONE),

	/* GPP_E21 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_E21, NATIVE, DEEP, OFF, ACPI),

	/* GPP_E22 - GPIO */
	PAD_CFG_GPO(GPP_E22, 0, DEEP),

	/* GPP_E23 - GPIO */
	PAD_NC(GPP_E23, NONE),

	/* GPP_E_CLK_LOOPBK - GPIO */
	PAD_NC(GPP_E_CLK_LOOPBK, NONE),

	/* ------- GPIO Community 5 ------- */

	/* ------- GPIO Group GPP_R ------- */

	/* GPP_R0 - HDA_BCLK */
	PAD_CFG_NF(GPP_R0, NONE, DEEP, NF1),

	/* GPP_R1 - HDA_SYNC */
	PAD_CFG_NF(GPP_R1, NATIVE, DEEP, NF1),

	/* GPP_R2 - HDA_SDO */
	PAD_CFG_NF(GPP_R2, NATIVE, DEEP, NF1),

	/* GPP_R3 - HDA_SDI0 */
	PAD_CFG_NF(GPP_R3, NATIVE, DEEP, NF1),

	/* GPP_R4 - HDA_RST# */
	PAD_CFG_NF(GPP_R4, NONE, DEEP, NF1),

	/* GPP_R5 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_R5, NONE, DEEP, OFF, ACPI),

	/* GPP_R6 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_R6, NONE, DEEP, OFF, ACPI),

	/* GPP_R7 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_R7, NONE, DEEP, OFF, ACPI),
};

void mainboard_configure_gpios(void)
{
	gpio_configure_pads(gpio_table, ARRAY_SIZE(gpio_table));
}
