/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef CFG_GPIO_H
#define CFG_GPIO_H

#include <gpio.h>

/*
 * Bidirectional GPIO port when both RX and TX buffer is enabled
 * TODO: move this macros to src/soc/intel/common/block/include/intelblocks/gpio_defs.h
 */
#ifndef PAD_CFG_GPIO_BIDIRECT_IOS
#define PAD_CFG_GPIO_BIDIRECT_IOS(pad, val, pull, rst, trig, iosstate, iosterm, own) \
	_PAD_CFG_STRUCT(pad,						\
		PAD_FUNC(GPIO) | PAD_RESET(rst) | PAD_TRIG(trig) |	\
		PAD_BUF(NO_DISABLE) | val,				\
		PAD_PULL(pull) | PAD_CFG_OWN_GPIO(own) |		\
		PAD_IOSSTATE(iosstate) | PAD_IOSTERM(iosterm))
#endif

#ifndef PAD_CFG_GPIO_BIDIRECT
#define PAD_CFG_GPIO_BIDIRECT(pad, val, pull, rst, trig, own)		\
	_PAD_CFG_STRUCT(pad,						\
		PAD_FUNC(GPIO) | PAD_RESET(rst) | PAD_TRIG(trig) |	\
		PAD_BUF(NO_DISABLE) | val,				\
		PAD_PULL(pull) | PAD_CFG_OWN_GPIO(own))
#endif


/* Pad configuration was generated automatically using intelp2m utility */
static const struct pad_config gpio_table[] = {

	/* ----- GPIO Community NorthWest ----- */

	/* ------- GPIO Group NorthWest ------- */

	/* GPIO_0 - JTAG_TCK */
	PAD_CFG_NF(GPIO_0, DN_20K, DEEP, NF1),
	/* GPIO_1 - JTAG_TRST_N */
	PAD_CFG_NF(GPIO_1, DN_20K, DEEP, NF1),
	/* GPIO_2 - JTAG_TMS */
	PAD_CFG_NF(GPIO_2, UP_20K, DEEP, NF1),
	/* GPIO_3 - JTAG_TDI */
	PAD_CFG_NF(GPIO_3, UP_20K, DEEP, NF1),
	/* GPIO_4 - JTAG_TDO */
	PAD_CFG_NF(GPIO_4, UP_20K, DEEP, NF1),
	/* GPIO_5 - JTAGX */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_5, UP_20K, DEEP, NF1, IGNORE, ENPU),
	/* GPIO_6 - JTAG_PREQ_N */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_6, UP_20K, DEEP, NF1, IGNORE, ENPU),
	/* GPIO_7 - JTAG_PRDY_N */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_7, UP_20K, DEEP, NF1, IGNORE, ENPU),
	/* GPIO_8 - n/a */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_8, DN_20K, PWROK, NF5, HIZCRx0, ENPD),
	/* GPIO_9 - n/a */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_9, DN_20K, PWROK, NF5, HIZCRx0, ENPD),
	/* GPIO_10 - n/a */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_10, DN_20K, PWROK, NF5, HIZCRx0, ENPD),
	/* GPIO_11 - n/a */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_11, DN_20K, PWROK, NF5, HIZCRx0, ENPD),
	/* GPIO_12 - n/a */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_12, DN_20K, PWROK, NF5, HIZCRx0, ENPD),
	/* GPIO_13 - n/a */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_13, DN_20K, DEEP, NF5, HIZCRx0, ENPD),
	/* GPIO_14 - n/a */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_14, DN_20K, DEEP, NF5, HIZCRx0, ENPD),
	/* GPIO_15 - n/a */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_15, DN_20K, DEEP, NF5, HIZCRx0, ENPD),
	/* GPIO_16 - n/a */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_16, DN_20K, DEEP, NF5, HIZCRx0, ENPD),
	/* GPIO_17 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_17, 0, DEEP, UP_20K, TxDRxE, ENPU),
	/* GPIO_18 - GPIO */
	PAD_CFG_GPI_APIC_IOS(GPIO_18, UP_20K, DEEP, LEVEL, NONE, IGNORE, ENPU),
	/* GPIO_19 - GPIO */
	PAD_CFG_GPI_APIC_IOS(GPIO_19, UP_20K, DEEP, EDGE_SINGLE, NONE, TxDRxE, ENPU),
	/* GPIO_20 - GPIO */
	PAD_CFG_GPI_APIC_IOS(GPIO_20, NONE, DEEP, LEVEL, NONE, IGNORE, SAME),
	/* GPIO_21 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_21, 1, DEEP, UP_20K, TxLASTRxE, ENPU),
	/* GPIO_22 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_22, 1, DEEP, UP_20K, TxDRxE, ENPU),
	/* GPIO_23 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_23, 1, DEEP, UP_20K, TxLASTRxE, ENPU),
	/* GPIO_24 - GPIO */
	PAD_CFG_GPI_TRIG_IOS_OWN(GPIO_24, UP_20K, DEEP, OFF, TxLASTRxE, ENPU, ACPI),
	/* GPIO_25 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_25, 1, DEEP, UP_20K, TxLASTRxE, ENPU),
	/* GPIO_26 - GPIO */
	PAD_CFG_GPI_SCI_IOS(GPIO_26, UP_20K, DEEP, EDGE_SINGLE, INVERT, IGNORE, ENPU),
	/* GPIO_27 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_27, 1, DEEP, NONE, IGNORE, DISPUPD),
	/* GPIO_28 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_28, 1, DEEP, UP_20K, TxLASTRxE, ENPU),
	/* GPIO_29 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_29, 1, DEEP, UP_20K, HIZCRx1, DISPUPD),
	/* GPIO_30 - n/a */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_30, DN_20K, DEEP, NF1, IGNORE, ENPD),
	/* GPIO_31 - n/a */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_31, DN_20K, DEEP, NF1, IGNORE, ENPD),
	/* GPIO_32 - n/a */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_32, DN_20K, DEEP, NF1, IGNORE, ENPD),
	/* GPIO_33 - n/a */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_33, DN_20K, DEEP, NF1, IGNORE, ENPD),
	/* GPIO_34 - n/a */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_34, DN_20K, DEEP, NF1, IGNORE, ENPD),
	/* GPIO_35 - SPKR */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_35, UP_20K, DEEP, NF4, IGNORE, ENPU),
	/* GPIO_36 - BSSB_DI */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_36, UP_20K, DEEP, NF6, IGNORE, ENPU),
	/* GPIO_37 - n/a */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_37, UP_20K, DEEP, NF1, IGNORE, ENPU),
	/* GPIO_38 - n/a */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_38, UP_20K, DEEP, NF1, IGNORE, ENPU),
	/* GPIO_39 - n/a */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_39, DN_20K, DEEP, NF1, IGNORE, ENPD),
	/* GPIO_40 - GPIO */
	PAD_CFG_GPIO_HI_Z(GPIO_40, UP_20K, DEEP, IGNORE, ENPU),
	/* GPIO_41 - n/a */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_41, UP_20K, DEEP, NF1, IGNORE, ENPU),
	/* GPIO_42 - MDSI_A_TE */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_42, DN_20K, DEEP, NF1, TxLASTRxE, ENPD),
	/* GPIO_43 - MDSI_C_TE */
	PAD_CFG_NF(GPIO_43, NONE, DEEP, NF1),
	/* GPIO_44 - USB2_OC0_N */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_44, UP_20K, DEEP, NF1, TxLASTRxE, ENPU),
	/* GPIO_45 - USB2_OC1_N */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_45, UP_20K, DEEP, NF1, TxLASTRxE, ENPU),
	/* GPIO_46 - MIPI_I2C_SDA */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_46, NONE, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_47 - MIPI_I2C_SCL */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_47, NONE, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_48 - PMC_I2C_SDA */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_48, UP_1K, DEEP, NF1, IGNORE, ENPU),
	/* GPIO_49 - PMC_I2C_SCL */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_49, UP_1K, DEEP, NF1, IGNORE, ENPU),
	/* GPIO_50 - SIO_I2C0_SDA */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_50, UP_1K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_51 - SIO_I2C0_SCL */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_51, UP_1K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_52 - SIO_I2C1_SDA */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_52, UP_1K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_53 - SIO_I2C1_SCL */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_53, UP_1K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_54 - GPIO */
	PAD_CFG_GPIO_HI_Z(GPIO_54, UP_1K, DEEP, HIZCRx1, ENPU),
	/* GPIO_55 - GPIO */
	PAD_CFG_GPIO_HI_Z(GPIO_55, UP_1K, DEEP, HIZCRx1, ENPU),
	/* GPIO_56 - SIO_I2C3_SDA */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_56, UP_1K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_57 - SIO_I2C3_SCL */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_57, UP_1K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_58 - SIO_I2C4_SDA */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_58, UP_1K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_59 - SIO_I2C4_SCL */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_59, UP_1K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_60 - SIO_UART0_RXD */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_60, UP_20K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_61 - SIO_UART0_TXD */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_61, UP_20K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_62 - SIO_UART0_RTS_N */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_62, UP_20K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_63 - SIO_UART0_CTS_N */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_63, UP_20K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_64 - SIO_UART2_RXD */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_64, UP_20K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_65 - SIO_UART2_TXD */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_65, UP_20K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_66 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_66, 1, DEEP, UP_20K, TxLASTRxE, ENPU),
	/* GPIO_67 - SIO_UART2_CTS_N */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_67, NONE, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_68 - PMC_SPI_FS0 */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_68, UP_20K, DEEP, NF1, TxLASTRxE, ENPU),
	/* GPIO_69 - PMC_SPI_FS1 */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_69, NONE, DEEP, NF1, TxLASTRxE, ENPU),
	/* GPIO_70 - PMC_SPI_FS2 */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_70, DN_20K, DEEP, NF1, TxLASTRxE, ENPD),
	/* GPIO_71 - PMC_SPI_RXD */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_71, DN_20K, DEEP, NF1, TxLASTRxE, ENPD),
	/* GPIO_72 - PMC_SPI_TXD */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_72, DN_20K, DEEP, NF1, TxLASTRxE, ENPD),
	/* GPIO_73 - PMC_SPI_CLK */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_73, DN_20K, DEEP, NF1, TxLASTRxE, ENPD),
	/* GPIO_74 - THERMTRIP_N */
	PAD_CFG_NF(GPIO_74, UP_20K, DEEP, NF1),
	/* GPIO_75 - PROCHOT_N */
	PAD_CFG_NF(GPIO_75, UP_20K, DEEP, NF1),
	/* GPIO_211 - RESERVED */
	/* GPIO_212 - GPIO */
	PAD_CFG_GPI_TRIG_IOS_OWN(GPIO_212, UP_20K, DEEP, OFF, HIZCRx0, ENPU, ACPI),
	/* GPIO_213 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_213, 1, DEEP, UP_20K, HIZCRx0, ENPU),
	/* GPIO_214 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_214, 1, DEEP, NONE, IGNORE, SAME),
	
	/* --- GPIO Community North --- */

	/* ----- GPIO Group North ----- */

	/* GPIO_76 - SVID0_ALERT_N */
	PAD_CFG_NF_IOSTANDBY_IGNORE(GPIO_76, NONE, DEEP, NF1),
	/* GPIO_77 - SVID0_DATA */
	PAD_CFG_NF_IOSTANDBY_IGNORE(GPIO_77, NONE, DEEP, NF1),
	/* GPIO_78 - SVID0_CLK */
	PAD_CFG_NF_IOSTANDBY_IGNORE(GPIO_78, NONE, DEEP, NF1),
	/* GPIO_79 - SIO_SPI_0_CLK */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_79, DN_20K, DEEP, NF1, IGNORE, ENPD),
	/* GPIO_80 - SIO_SPI_0_FS0 */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_80, DN_20K, DEEP, NF1, IGNORE, ENPD),
	/* GPIO_81 - FST_SPI_CS2_N */
	PAD_CFG_NF_IOSTANDBY_IGNORE(GPIO_81, NONE, DEEP, NF3),
	/* GPIO_82 - SIO_SPI_0_RXD */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_82, DN_20K, DEEP, NF1, IGNORE, ENPD),
	/* GPIO_83 - SIO_SPI_0_TXD */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_83, DN_20K, DEEP, NF1, IGNORE, ENPD),
	/* GPIO_84 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPIO_84, DN_20K, DEEP, OFF, ACPI),
	/* GPIO_85 - GPIO */
	PAD_CFG_GPIO_HI_Z(GPIO_85, DN_20K, DEEP, TxLASTRxE, SAME),
	/* GPIO_86 - GPIO */
	PAD_CFG_GPIO_HI_Z(GPIO_86, DN_20K, DEEP, TxLASTRxE, SAME),
	/* GPIO_87 - GPIO */
	PAD_CFG_GPIO_HI_Z(GPIO_87, DN_20K, DEEP, TxLASTRxE, SAME),
	/* GPIO_88 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPIO_88, DN_20K, DEEP, OFF, ACPI),
	/* GPIO_89 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPIO_89, DN_20K, DEEP, OFF, ACPI),
	/* GPIO_90 - FST_SPI_CS0_N */
	PAD_CFG_NF(GPIO_90, NATIVE, DEEP, NF1),
	/* GPIO_91 - FST_SPI_CS1_N */
	PAD_CFG_NF(GPIO_91, NATIVE, DEEP, NF1),
	/* GPIO_92 - FST_SPI_MOSI_IO0 */
	PAD_CFG_NF(GPIO_92, NATIVE, DEEP, NF1),
	/* GPIO_93 - FST_SPI_MISO_IO1 */
	PAD_CFG_NF(GPIO_93, NATIVE, DEEP, NF1),
	/* GPIO_94 - FST_SPI_IO2 */
	PAD_CFG_NF(GPIO_94, NATIVE, DEEP, NF1),
	/* GPIO_95 - FST_SPI_IO3 */
	PAD_CFG_NF(GPIO_95, NATIVE, DEEP, NF1),
	/* GPIO_96 - FST_SPI_CLK */
	PAD_CFG_NF(GPIO_96, NATIVE, DEEP, NF1),
	/* GPIO_97 - FST_SPI_CLK_FB */
	PAD_CFG_NF(GPIO_97, NATIVE, DEEP, NF1),
	/* GPIO_98 - PMU_PLTRST_N */
	PAD_CFG_NF_IOSTANDBY_IGNORE(GPIO_98, NONE, DEEP, NF1),
	/* GPIO_99 - PMU_PWRBTN_N */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_99, UP_20K, DEEP, NF1, IGNORE, ENPU),
	/* GPIO_100 - PMU_SLP_S0_N */
	PAD_CFG_NF_IOSTANDBY_IGNORE(GPIO_100, NONE, DEEP, NF1),
	/* GPIO_101 - PMU_SLP_S3_N */
	PAD_CFG_NF_IOSTANDBY_IGNORE(GPIO_101, NONE, DEEP, NF1),
	/* GPIO_102 - PMU_SLP_S4_N */
	PAD_CFG_NF_IOSTANDBY_IGNORE(GPIO_102, NONE, DEEP, NF1),
	/* GPIO_103 - SUSPWRDNACK */
	PAD_CFG_NF_IOSTANDBY_IGNORE(GPIO_103, NONE, DEEP, NF1),
	/* GPIO_104 - EMMC_PWR_EN_N */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_104, UP_20K, DEEP, NF1, IGNORE, ENPU),
	/* GPIO_105 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_105, 1, DEEP, UP_20K, IGNORE, ENPU),
	/* GPIO_106 - PMU_BATLOW_N */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_106, UP_20K, DEEP, NF1, IGNORE, ENPU),
	/* GPIO_107 - PMU_RSTBTN_N */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_107, UP_20K, DEEP, NF1, IGNORE, ENPU),
	/* GPIO_108 - PMU_SUSCLK */
	PAD_CFG_NF_IOSTANDBY_IGNORE(GPIO_108, NONE, DEEP, NF1),
	/* GPIO_109 - SUS_STAT_N */
	PAD_CFG_NF_IOSTANDBY_IGNORE(GPIO_109, NONE, DEEP, NF1),
	/* GPIO_110 - ISH_I2C0_SDA */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_110, UP_1K, DEEP, NF2, IGNORE, ENPU),
	/* GPIO_111 - ISH_I2C0_SCL */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_111, UP_1K, DEEP, NF2, IGNORE, ENPU),
	/* GPIO_112 - ISH_I2C1_SDA */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_112, UP_1K, DEEP, NF2, IGNORE, ENPU),
	/* GPIO_113 - ISH_I2C1_ScL */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_113, UP_1K, DEEP, NF2, IGNORE, ENPU),
	/* GPIO_114 - SIO_I2C7_SDA */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_114, UP_1K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_115 - SIO_I2C7_SCL */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_115, UP_1K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_116 - PCIE_WAKE0_N */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_116, UP_20K, DEEP, NF1, IGNORE, ENPU),
	/* GPIO_117 - PCIE_WAKE1_N */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_117, UP_20K, DEEP, NF1, IGNORE, ENPU),
	/* GPIO_118 - PCIE_WAKE2_N */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_118, UP_20K, DEEP, NF1, IGNORE, ENPU),
	/* GPIO_119 - PCIE_WAKE3_N */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_119, UP_20K, DEEP, NF1, IGNORE, ENPU),
	/* GPIO_120 - PCIE_CLKREQ0_N */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_120, UP_20K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_121 - PCIE_CLKREQ1_N */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_121, UP_20K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_122 - PCIE_CLKREQ2_N */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_122, UP_20K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_123 - PCIE_CLKREQ3_N */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_123, UP_20K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_124 - DDI0_DDC_SDA */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_124, NONE, DEEP, NF1, HIZCRx0, ENPU),
	/* GPIO_125 - DDI0_DDC_SCL */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_125, NONE, DEEP, NF1, HIZCRx0, ENPU),
	/* GPIO_126 - DDI1_DDC_SDA */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_126, UP_20K, DEEP, NF1, HIZCRx0, ENPU),
	/* GPIO_127 - DDI1_DDC_SCL */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_127, UP_20K, DEEP, NF1, HIZCRx0, ENPU),
	/* GPIO_128 - PNL0_VDDEN */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_128, DN_20K, DEEP, NF1, Tx0RxDCRx0, ENPD),
	/* GPIO_129 - PNL0_BKLTEN */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_129, DN_20K, DEEP, NF1, Tx0RxDCRx0, ENPD),
	/* GPIO_130 - PNL0_BKLCTL */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_130, DN_20K, DEEP, NF1, Tx0RxDCRx0, ENPD),
	/* GPIO_131 - DDI0_HPD */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_131, UP_20K, DEEP, NF1, TxDRxE, ENPU),
	/* GPIO_132 - DDI1_HPD */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_132, UP_20K, DEEP, NF1, TxDRxE, ENPU),
	/* GPIO_133 - DDI2_HPD */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_133, NONE, DEEP, NF1, TxDRxE, ENPU),
	/* GPIO_134 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_134, 1, DEEP, UP_20K, IGNORE, ENPU),
	/* GPIO_135 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_135, 1, DEEP, UP_20K, IGNORE, ENPU),
	/* GPIO_136 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_136, 0, DEEP, UP_20K, IGNORE, ENPU),
	/* GPIO_137 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_137, 1, DEEP, UP_20K, IGNORE, ENPU),
	/* GPIO_138 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_138, 1, DEEP, NONE, TxLASTRxE, ENPU),
	/* GPIO_139 - SATA_GP1 */
	PAD_CFG_NF(GPIO_139, NONE, DEEP, NF5),
	/* GPIO_140 - SATA_DEVSLP0 */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_140, DN_20K, DEEP, NF5, TxLASTRxE, ENPD),
	/* GPIO_141 - GPIO */
	PAD_CFG_GPIO_BIDIRECT_IOS(GPIO_141, 0, NONE, DEEP, OFF, HIZCRx1, ENPU, ACPI),
	/* GPIO_142 - SATA_LEDN */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_142, UP_20K, DEEP, NF5, HIZCRx1, ENPU),
	/* GPIO_143 - GPIO */
	PAD_CFG_GPI_TRIG_IOSSTATE_OWN(GPIO_143, NONE, DEEP, OFF, HIZCRx1, ACPI),
	/* GPIO_144 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_144, 0, DEEP, DN_20K, HIZCRx1, ENPD),
	/* GPIO_145 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_145, 0, DEEP, DN_20K, HIZCRx1, ENPD),
	/* GPIO_146 - n/a */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_146, UP_20K, DEEP, NF5, HIZCRx1, ENPU),
	/* GPIO_147 - LPC_SERIRQ */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_147, UP_20K, DEEP, NF1, TxLASTRxE, ENPU),
	/* GPIO_148 - LPC_CLKOUT0 */
	PAD_CFG_NF_IOSSTATE(GPIO_148, NONE, DEEP, NF1, HIZCRx1),
	/* GPIO_149 - LPC_CLKOUT1 */
	PAD_CFG_NF_IOSSTATE(GPIO_149, NONE, DEEP, NF1, HIZCRx1),
	/* GPIO_150 - LPC_AD0 */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_150, UP_20K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_151 - LPC_AD1 */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_151, UP_20K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_152 - LPC_AD2 */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_152, UP_20K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_153 - LPC_AD3 */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_153, UP_20K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_154 - LPC_CLKRUN_N */
	PAD_CFG_NF(GPIO_154, UP_20K, DEEP, NF1),
	/* GPIO_155 - LPC_FRAME_N */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_155, UP_20K, DEEP, NF1, HIZCRx1, ENPU),

	/* --- GPIO Community Audio --- */

	/* ----- GPIO Group Audio ----- */

	/* GPIO_156 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_156, 1, DEEP, UP_20K, IGNORE, ENPU),
	/* GPIO_157 - GPIO */
	PAD_CFG_GPI_TRIG_IOS_OWN(GPIO_157, DN_20K, DEEP, OFF, IGNORE, ENPD, ACPI),
	/* GPIO_158 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_158, 0, DEEP, DN_20K, IGNORE, ENPD),
	/* GPIO_159 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_159, 1, DEEP, UP_20K, TxDRxE, DISPUPD),
	/* GPIO_160 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_160, 0, DEEP, DN_20K, IGNORE, ENPD),
	/* GPIO_161 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_161, 1, DEEP, NONE, IGNORE, SAME),
	/* GPIO_162 - GPIO */
	PAD_CFG_GPIO_HI_Z(GPIO_162, UP_20K, DEEP, IGNORE, ENPU),
	/* GPIO_163 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_163, 1, DEEP, UP_20K, IGNORE, ENPU),
	/* GPIO_164 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_164, 1, DEEP, UP_5K, TxDRxE, ENPU),
	/* GPIO_165 - GPIO */
	PAD_CFG_GPI_TRIG_IOS_OWN(GPIO_165, DN_20K, DEEP, OFF, IGNORE, ENPD, ACPI),
	/* GPIO_166 - AVS_HDA_BCLK */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_166, DN_20K, DEEP, NF1, HIZCRx1, ENPD),
	/* GPIO_167 - AVS_HDA_WS_SYNC */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_167, DN_20K, DEEP, NF1, HIZCRx1, ENPD),
	/* GPIO_168 - AVS_HDA_SDI */
	PAD_CFG_NF_IOSSTATE(GPIO_168, NONE, DEEP, NF1, HIZCRx1),
	/* GPIO_169 - AVS_HDA_SDO */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_169, DN_20K, DEEP, NF1, HIZCRx1, ENPD),
	/* GPIO_170 - AVS_HDA_RST_N */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_170, DN_20K, DEEP, NF1, HIZCRx1, ENPD),
	/* GPIO_171 - AVS_DMIC_CLK_A1 */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_171, DN_20K, DEEP, NF1, HIZCRx1, ENPD),
	/* GPIO_172 - AVS_DMIC_CLK_B1 */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_172, DN_20K, DEEP, NF1, HIZCRx1, ENPD),
	/* GPIO_173 - AVS_DMIC_DATA_1 */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_173, DN_20K, DEEP, NF1, HIZCRx1, ENPD),
	/* GPIO_174 - AVS_DMIC_CLK_AB2 */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_174, DN_20K, DEEP, NF1, HIZCRx1, ENPD),
	/* GPIO_175 - AVS_DMIC_DATA_2 */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_175, DN_20K, DEEP, NF1, HIZCRx1, ENPD),

	/* --- GPIO Community SCC --- */

	/* ----- GPIO Group SCC ----- */

	/* GPIO_176 - SMB_ALERT_N */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_176, UP_20K, PWROK, NF1, IGNORE, ENPU),
	/* GPIO_177 - SMB_CLK */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_177, UP_5K, PWROK, NF1, IGNORE, ENPU),
	/* GPIO_178 - SMB_DATA */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_178, UP_5K, PWROK, NF1, IGNORE, ENPU),
	/* GPIO_187 - SDCARD_LVL_WP */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_187, UP_20K, DEEP, NF1, IGNORE, ENPU),
	/* GPIO_179 - SDCARD_CLK */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_179, DN_20K, DEEP, NF1, HIZCRx0, ENPD),
	/* GPIO_180 - SDCARD_CLK_FB */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_180, DN_20K, DEEP, NF1, TxLASTRxE, ENPD),
	/* GPIO_181 - SDCARD_D0 */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_181, UP_20K, DEEP, NF1, HIZCRx0, DISPUPD),
	/* GPIO_182 - SDCARD_D1 */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_182, UP_20K, DEEP, NF1, HIZCRx0, DISPUPD),
	/* GPIO_183 - SDCARD_D2 */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_183, UP_20K, DEEP, NF1, HIZCRx0, DISPUPD),
	/* GPIO_184 - SDCARD_D3 */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_184, UP_20K, DEEP, NF1, HIZCRx0, DISPUPD),
	/* GPIO_185 - SDCARD_CMD */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_185, UP_20K, DEEP, NF1, HIZCRx0, DISPUPD),
	/* GPIO_186 - GPIO */
	PAD_CFG_GPI_TRIG_IOSSTATE_OWN(GPIO_186, NONE, DEEP, EDGE_SINGLE, TxDRxE, ACPI),
	/* GPIO_188 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_188, 0, DEEP, DN_20K, TxLASTRxE, ENPD),
	/* GPIO_210 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_210, 1, DEEP, UP_20K, HIZCRx0, ENPD),
	/* GPIO_189 - OSC_CLK_OUT_0 */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_189, DN_20K, DEEP, NF1, HIZCRx0, ENPD),
	/* GPIO_190 - OSC_CLK_OUT_1 */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_190, DN_20K, DEEP, NF1, HIZCRx0, ENPD),
	/* GPIO_191 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_191, 1, DEEP, NONE, IGNORE, SAME),
	/* GPIO_192 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_192, 1, DEEP, UP_20K, IGNORE, ENPU),
	/* GPIO_193 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_193, 1, DEEP, NONE, IGNORE, SAME),
	/* GPIO_194 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_194, 1, DEEP, UP_20K, IGNORE, ENPU),
	/* GPIO_195 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_195, 1, DEEP, NONE, IGNORE, SAME),
	/* GPIO_196 - GPIO */
	PAD_CFG_GPO_IOSSTATE_IOSTERM(GPIO_196, 1, DEEP, NONE, IGNORE, SAME),
	/* GPIO_197 - n/a */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_197, DN_20K, DEEP, NF2, TxLASTRxE, ENPD),
	/* GPIO_198 - EMMC_CLK */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_198, DN_20K, DEEP, NF1, HIZCRx0, ENPD),
	/* GPIO_199 - EMMC_D0 */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_199, DN_20K, DEEP, NF1, TxLASTRxE, ENPD),
	/* GPIO_200 - EMMC_D1 */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_200, UP_20K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_201 - EMMC_D2 */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_201, UP_20K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_202 - EMMC_D3 */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_202, UP_20K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_203 - EMMC_D4 */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_203, UP_20K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_204 - EMMC_D5 */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_204, UP_20K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_205 - EMMC_D6 */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_205, UP_20K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_206 - EMMC_D7 */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_206, UP_20K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_207 - EMMC_CMD */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_207, UP_20K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_208 - EMMC_RCLK */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_208, UP_20K, DEEP, NF1, HIZCRx1, ENPU),
	/* GPIO_209 - EMMC_RST_N */
	PAD_CFG_NF_IOSSTATE_IOSTERM(GPIO_209, DN_20K, DEEP, NF1, HIZCRx0, ENPD),
	
};

#endif /* CFG_GPIO_H */
