/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef _FSP2_0_STATUS_X64_TO_X86_H_
#define _FSP2_0_STATUS_X64_TO_X86_H_

/* Fixup definitions for x86_64 mode when FSP uses 32bit mode */
#if CONFIG(PLATFORM_USES_FSP2_X86_32) && CONFIG(USE_X86_64_SUPPORT)

#undef MAX_BIT
#undef ENCODE_RESET_REQUEST
#undef FSP_STATUS_RESET_REQUIRED_COLD
#undef FSP_STATUS_RESET_REQUIRED_WARM
#undef FSP_STATUS_RESET_REQUIRED_3
#undef FSP_STATUS_RESET_REQUIRED_4
#undef FSP_STATUS_RESET_REQUIRED_5
#undef FSP_STATUS_RESET_REQUIRED_6
#undef FSP_STATUS_RESET_REQUIRED_7
#undef FSP_STATUS_RESET_REQUIRED_8
#undef FSP_STATUS_VARIABLE_REQUEST

#undef EFI_SUCCESS
#undef EFI_INVALID_PARAMETER
#undef EFI_UNSUPPORTED
#undef EFI_DEVICE_ERROR
#undef EFI_NOT_FOUND
#undef EFI_NOT_STARTED

#define MAX_BIT				0x80000000
#define ENCODE_RESET_REQUEST(ResetType)	\
		((UINT32)((MAX_BIT >> 1) | (ResetType)))
#define FSP_STATUS_RESET_REQUIRED_COLD	ENCODE_RESET_REQUEST(1)
#define FSP_STATUS_RESET_REQUIRED_WARM	ENCODE_RESET_REQUEST(2)
#define FSP_STATUS_RESET_REQUIRED_3	ENCODE_RESET_REQUEST(3)
#define FSP_STATUS_RESET_REQUIRED_4	ENCODE_RESET_REQUEST(4)
#define FSP_STATUS_RESET_REQUIRED_5	ENCODE_RESET_REQUEST(5)
#define FSP_STATUS_RESET_REQUIRED_6	ENCODE_RESET_REQUEST(6)
#define FSP_STATUS_RESET_REQUIRED_7	ENCODE_RESET_REQUEST(7)
#define FSP_STATUS_RESET_REQUIRED_8	ENCODE_RESET_REQUEST(8)
#define FSP_STATUS_VARIABLE_REQUEST	ENCODE_RESET_REQUEST(10)

#define ENCODE_EFI_STATUS(Status)	\
		((UINT32)((MAX_BIT) | (Status)))

#define EFI_SUCCESS			0
#define EFI_INVALID_PARAMETER		ENCODE_EFI_STATUS(2)
#define EFI_UNSUPPORTED			ENCODE_EFI_STATUS(3)
#define EFI_DEVICE_ERROR		ENCODE_EFI_STATUS(7)
#define EFI_NOT_FOUND			ENCODE_EFI_STATUS(14)
#define EFI_NOT_STARTED			ENCODE_EFI_STATUS(19)

#endif

#endif  /* _FSP2_0_STATUS_X64_TO_X86_H_ */