/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef CFG_GPIO_H
#define CFG_GPIO_H

#include <gpio.h>

static const struct pad_config gpio_table[] = {

	/* ------- GPIO Community 0 ------- */

	/* ------- GPIO Group GPP_G ------- */

	/* GPP_G00 - SD_SDIO_CMD */
	PAD_CFG_NF(GPP_G00, NONE, DEEP, NF1),
	/* GPP_G01 - SD_SDIO_D0 */
	PAD_CFG_NF(GPP_G01, NONE, DEEP, NF1),
	/* GPP_G02 - SD_SDIO_D1 */
	PAD_CFG_NF(GPP_G02, NONE, DEEP, NF1),
	/* GPP_G03 - SD_SDIO_D2 */
	PAD_CFG_NF(GPP_G03, NONE, DEEP, NF1),
	/* GPP_G04 - SD_SDIO_D3 */
	PAD_CFG_NF(GPP_G04, NONE, DEEP, NF1),
	/* GPP_G05 - SD_SDIO_CD_N */
	PAD_CFG_NF(GPP_G05, NONE, DEEP, NF1),
	/* GPP_G06 - SD_SDIO_CLK */
	PAD_CFG_NF(GPP_G06, NONE, DEEP, NF1),
	/* GPP_G07 - SD_SDIO_WP */
	PAD_CFG_NF(GPP_G07, NONE, DEEP, NF1),


	/* ------- GPIO Community 1 ------- */

	/* ------- GPIO Group HVCMOS ------- */

	/* ------- GPIO Group GPP_E ------- */

	/* GPP_E00 - GPIO */
	PAD_NC(GPP_E00, NONE),
	/* GPP_E01 - GPIO */
	PAD_NC(GPP_E01, NONE),
	/* GPP_E02 - GPIO */
	PAD_NC(GPP_E02, NONE),
	/* GPP_E03 - GPIO */
	PAD_NC(GPP_E03, NONE),
	/* GPP_E04 - GPIO */
	PAD_NC(GPP_E04, NONE),
	/* GPP_E05 - SATA_LED_N */
	PAD_CFG_NF(GPP_E05, NONE, DEEP, NF1),
	/* GPP_E06 - GPIO */
	PAD_NC(GPP_E06, NONE),
	/* GPP_E07 - GPIO */
	PAD_NC(GPP_E07, NONE),
	/* GPP_E08 - GPIO */
	PAD_NC(GPP_E08, NONE),
	/* GPP_E09 - GPIO */
	PAD_NC(GPP_E09, NONE),
	/* GPP_E10 - GPIO */
	PAD_NC(GPP_E10, NONE),
	/* GPP_E11 - GPIO */
	PAD_NC(GPP_E11, NONE),
	/* GPP_E12 - GPIO */
	PAD_NC(GPP_E12, NONE),
	/* GPP_E13 - GPIO */
	PAD_NC(GPP_E13, NONE),
	/* GPP_E14 - GPIO */
	PAD_NC(GPP_E14, NONE),
	/* GPP_E15 - DDI1_DDC_SCL */
	PAD_CFG_NF(GPP_E15, NONE, PLTRST, NF1),
	/* GPP_E16 - DDI1_DDC_SDA */
	PAD_CFG_NF(GPP_E16, NONE, PLTRST, NF1),
	/* GPP_E17 - DDI2_DDC_SCL */
	PAD_CFG_NF(GPP_E17, NONE, DEEP, NF1),
	/* GPP_E18 - DDI2_DDC_SDA */
	PAD_CFG_NF(GPP_E18, NONE, DEEP, NF1),
	/* GPP_E19 - GPIO */
	PAD_NC(GPP_E19, NONE),
	/* GPP_E20 - GPIO */
	PAD_NC(GPP_E20, NONE),
	/* GPP_E21 - GPIO */
	PAD_NC(GPP_E21, NONE),
	/* GPP_E22 - GPIO */
	PAD_NC(GPP_E22, NONE),
	/* GPP_E23 - GPIO */
	PAD_NC(GPP_E23, NONE),

	/* ------- GPIO Group JTAG ------- */

	/* ------- GPIO Group VGPIO_LNK ------- */

	/* VGPIO_LNK_DN_0 - VGPIO_LNK_DN_0 */
	PAD_CFG_NF(VGPIO_LNK_DN_0, NONE, DEEP, NF1),
	/* VGPIO_LNK_DN_1 - VGPIO_LNK_DN_1 */
	PAD_CFG_NF(VGPIO_LNK_DN_1, NONE, DEEP, NF1),
	/* VGPIO_LNK_DN_2 - VGPIO_LNK_DN_2 */
	PAD_CFG_NF(VGPIO_LNK_DN_2, NONE, DEEP, NF1),
	/* VGPIO_LNK_DN_3 - VGPIO_LNK_DN_3 */
	PAD_CFG_NF(VGPIO_LNK_DN_3, NONE, DEEP, NF1),

	/* ------- GPIO Community 2 ------- */

	/* ------- GPIO Group CPU ------- */

	/* ------- GPIO Group VGPIO_PCIE ------- */

	/* VGPIO_PCIE0 - VGPIO_PCIE0 */
	PAD_CFG_NF(VGPIO_PCIE0, NONE, PLTRST, NF1),
	/* VGPIO_PCIE1 - VGPIO_PCIE1 */
	PAD_CFG_NF(VGPIO_PCIE1, NONE, PLTRST, NF1),
	/* VGPIO_PCIE2 - VGPIO_PCIE2 */
	PAD_CFG_NF(VGPIO_PCIE2, NONE, PLTRST, NF1),
	/* VGPIO_PCIE3 - VGPIO_PCIE3 */
	PAD_CFG_NF(VGPIO_PCIE3, NONE, PLTRST, NF1),
	/* VGPIO_PCIE4 - VGPIO_PCIE4 */
	PAD_CFG_NF(VGPIO_PCIE4, NONE, PLTRST, NF1),
	/* VGPIO_PCIE5 - VGPIO_PCIE5 */
	PAD_CFG_NF(VGPIO_PCIE5, NONE, PLTRST, NF1),
	/* VGPIO_PCIE6 - VGPIO_PCIE6 */
	PAD_CFG_NF(VGPIO_PCIE6, NONE, PLTRST, NF1),
	/* VGPIO_PCIE7 - VGPIO_PCIE7 */
	PAD_CFG_NF(VGPIO_PCIE7, NONE, PLTRST, NF1),
	/* VGPIO_PCIE8 - VGPIO_PCIE8 */
	PAD_CFG_NF(VGPIO_PCIE8, NONE, PLTRST, NF1),
	/* VGPIO_PCIE9 - VGPIO_PCIE9 */
	PAD_CFG_NF(VGPIO_PCIE9, NONE, PLTRST, NF1),
	/* VGPIO_PCIE10 - VGPIO_PCIE10 */
	PAD_CFG_NF(VGPIO_PCIE10, NONE, PLTRST, NF1),
	/* VGPIO_PCIE11 - VGPIO_PCIE11 */
	PAD_CFG_NF(VGPIO_PCIE11, NONE, PLTRST, NF1),
	/* VGPIO_PCIE12 - VGPIO_PCIE12 */
	PAD_CFG_NF(VGPIO_PCIE12, NONE, PLTRST, NF1),
	/* VGPIO_PCIE13 - VGPIO_PCIE13 */
	PAD_CFG_NF(VGPIO_PCIE13, NONE, PLTRST, NF1),
	/* VGPIO_PCIE14 - VGPIO_PCIE14 */
	PAD_CFG_NF(VGPIO_PCIE14, NONE, PLTRST, NF1),
	/* VGPIO_PCIE15 - VGPIO_PCIE15 */
	PAD_CFG_NF(VGPIO_PCIE15, NONE, PLTRST, NF1),
	/* VGPIO_PCIE16 - VGPIO_PCIE16 */
	PAD_CFG_NF(VGPIO_PCIE16, NONE, PLTRST, NF1),
	/* VGPIO_PCIE17 - VGPIO_PCIE17 */
	PAD_CFG_NF(VGPIO_PCIE17, NONE, PLTRST, NF1),
	/* VGPIO_PCIE18 - VGPIO_PCIE18 */
	PAD_CFG_NF(VGPIO_PCIE18, NONE, PLTRST, NF1),
	/* VGPIO_PCIE19 - VGPIO_PCIE19 */
	PAD_CFG_NF(VGPIO_PCIE19, NONE, PLTRST, NF1),
	/* VGPIO_PCIE20 - VGPIO_PCIE20 */
	PAD_CFG_NF(VGPIO_PCIE20, NONE, PLTRST, NF1),
	/* VGPIO_PCIE21 - VGPIO_PCIE21 */
	PAD_CFG_NF(VGPIO_PCIE21, NONE, PLTRST, NF1),
	/* VGPIO_PCIE22 - VGPIO_PCIE22 */
	PAD_CFG_NF(VGPIO_PCIE22, NONE, PLTRST, NF1),
	/* VGPIO_PCIE23 - VGPIO_PCIE23 */
	PAD_CFG_NF(VGPIO_PCIE23, NONE, PLTRST, NF1),
	/* VGPIO_PCIE24 - VGPIO_PCIE24 */
	PAD_CFG_NF(VGPIO_PCIE24, NONE, PLTRST, NF1),
	/* VGPIO_PCIE25 - VGPIO_PCIE25 */
	PAD_CFG_NF(VGPIO_PCIE25, NONE, PLTRST, NF1),
	/* VGPIO_PCIE26 - VGPIO_PCIE26 */
	PAD_CFG_NF(VGPIO_PCIE26, NONE, PLTRST, NF1),
	/* VGPIO_PCIE27 - VGPIO_PCIE27 */
	PAD_CFG_NF(VGPIO_PCIE27, NONE, PLTRST, NF1),
	/* VGPIO_PCIE28 - VGPIO_PCIE28 */
	PAD_CFG_NF(VGPIO_PCIE28, NONE, PLTRST, NF1),
	/* VGPIO_PCIE29 - VGPIO_PCIE29 */
	PAD_CFG_NF(VGPIO_PCIE29, NONE, PLTRST, NF1),
	/* VGPIO_PCIE30 - VGPIO_PCIE30 */
	PAD_CFG_NF(VGPIO_PCIE30, NONE, PLTRST, NF1),
	/* VGPIO_PCIE31 - VGPIO_PCIE31 */
	PAD_CFG_NF(VGPIO_PCIE31, NONE, PLTRST, NF1),
	/* VGPIO_PCIE32 - VGPIO_PCIE32 */
	PAD_CFG_NF(VGPIO_PCIE32, NONE, PLTRST, NF1),
	/* VGPIO_PCIE33 - VGPIO_PCIE33 */
	PAD_CFG_NF(VGPIO_PCIE33, NONE, PLTRST, NF1),
	/* VGPIO_PCIE34 - VGPIO_PCIE34 */
	PAD_CFG_NF(VGPIO_PCIE34, NONE, PLTRST, NF1),
	/* VGPIO_PCIE35 - VGPIO_PCIE35 */
	PAD_CFG_NF(VGPIO_PCIE35, NONE, PLTRST, NF1),
	/* VGPIO_PCIE36 - VGPIO_PCIE36 */
	PAD_CFG_NF(VGPIO_PCIE36, NONE, PLTRST, NF1),
	/* VGPIO_PCIE37 - VGPIO_PCIE37 */
	PAD_CFG_NF(VGPIO_PCIE37, NONE, PLTRST, NF1),
	/* VGPIO_PCIE38 - VGPIO_PCIE38 */
	PAD_CFG_NF(VGPIO_PCIE38, NONE, PLTRST, NF1),
	/* VGPIO_PCIE39 - VGPIO_PCIE39 */
	PAD_CFG_NF(VGPIO_PCIE39, NONE, PLTRST, NF1),
	/* VGPIO_PCIE40 - VGPIO_PCIE40 */
	PAD_CFG_NF(VGPIO_PCIE40, NONE, PLTRST, NF1),
	/* VGPIO_PCIE41 - VGPIO_PCIE41 */
	PAD_CFG_NF(VGPIO_PCIE41, NONE, PLTRST, NF1),
	/* VGPIO_PCIE42 - VGPIO_PCIE42 */
	PAD_CFG_NF(VGPIO_PCIE42, NONE, PLTRST, NF1),
	/* VGPIO_PCIE43 - VGPIO_PCIE43 */
	PAD_CFG_NF(VGPIO_PCIE43, NONE, PLTRST, NF1),
	/* VGPIO_PCIE44 - VGPIO_PCIE44 */
	PAD_CFG_NF(VGPIO_PCIE44, NONE, PLTRST, NF1),
	/* VGPIO_PCIE45 - VGPIO_PCIE45 */
	PAD_CFG_NF(VGPIO_PCIE45, NONE, PLTRST, NF1),
	/* VGPIO_PCIE46 - VGPIO_PCIE46 */
	PAD_CFG_NF(VGPIO_PCIE46, NONE, PLTRST, NF1),
	/* VGPIO_PCIE47 - VGPIO_PCIE47 */
	PAD_CFG_NF(VGPIO_PCIE47, NONE, PLTRST, NF1),
	/* VGPIO_PCIE48 - VGPIO_PCIE48 */
	PAD_CFG_NF(VGPIO_PCIE48, NONE, PLTRST, NF1),
	/* VGPIO_PCIE49 - VGPIO_PCIE49 */
	PAD_CFG_NF(VGPIO_PCIE49, NONE, PLTRST, NF1),
	/* VGPIO_PCIE50 - VGPIO_PCIE50 */
	PAD_CFG_NF(VGPIO_PCIE50, NONE, PLTRST, NF1),
	/* VGPIO_PCIE51 - VGPIO_PCIE51 */
	PAD_CFG_NF(VGPIO_PCIE51, NONE, PLTRST, NF1),
	/* VGPIO_PCIE52 - VGPIO_PCIE52 */
	PAD_CFG_NF(VGPIO_PCIE52, NONE, PLTRST, NF1),
	/* VGPIO_PCIE53 - VGPIO_PCIE53 */
	PAD_CFG_NF(VGPIO_PCIE53, NONE, PLTRST, NF1),
	/* VGPIO_PCIE54 - VGPIO_PCIE54 */
	PAD_CFG_NF(VGPIO_PCIE54, NONE, PLTRST, NF1),
	/* VGPIO_PCIE55 - VGPIO_PCIE55 */
	PAD_CFG_NF(VGPIO_PCIE55, NONE, PLTRST, NF1),
	/* VGPIO_PCIE56 - VGPIO_PCIE56 */
	PAD_CFG_NF(VGPIO_PCIE56, NONE, PLTRST, NF1),
	/* VGPIO_PCIE57 - VGPIO_PCIE57 */
	PAD_CFG_NF(VGPIO_PCIE57, NONE, PLTRST, NF1),
	/* VGPIO_PCIE58 - VGPIO_PCIE58 */
	PAD_CFG_NF(VGPIO_PCIE58, NONE, PLTRST, NF1),
	/* VGPIO_PCIE59 - VGPIO_PCIE59 */
	PAD_CFG_NF(VGPIO_PCIE59, NONE, PLTRST, NF1),
	/* VGPIO_PCIE60 - VGPIO_PCIE60 */
	PAD_CFG_NF(VGPIO_PCIE60, NONE, PLTRST, NF1),
	/* VGPIO_PCIE61 - VGPIO_PCIE61 */
	PAD_CFG_NF(VGPIO_PCIE61, NONE, PLTRST, NF1),
	/* VGPIO_PCIE62 - VGPIO_PCIE62 */
	PAD_CFG_NF(VGPIO_PCIE62, NONE, PLTRST, NF1),
	/* VGPIO_PCIE63 - VGPIO_PCIE63 */
	PAD_CFG_NF(VGPIO_PCIE63, NONE, PLTRST, NF1),
	/* VGPIO_PCIE64 - VGPIO_PCIE64 */
	PAD_CFG_NF(VGPIO_PCIE64, NONE, PLTRST, NF1),
	/* VGPIO_PCIE65 - VGPIO_PCIE65 */
	PAD_CFG_NF(VGPIO_PCIE65, NONE, PLTRST, NF1),
	/* VGPIO_PCIE66 - VGPIO_PCIE66 */
	PAD_CFG_NF(VGPIO_PCIE66, NONE, PLTRST, NF1),
	/* VGPIO_PCIE67 - VGPIO_PCIE67 */
	PAD_CFG_NF(VGPIO_PCIE67, NONE, PLTRST, NF1),
	/* VGPIO_PCIE68 - VGPIO_PCIE68 */
	PAD_CFG_NF(VGPIO_PCIE68, NONE, PLTRST, NF1),
	/* VGPIO_PCIE69 - VGPIO_PCIE69 */
	PAD_CFG_NF(VGPIO_PCIE69, NONE, PLTRST, NF1),
	/* VGPIO_PCIE70 - VGPIO_PCIE70 */
	PAD_CFG_NF(VGPIO_PCIE70, NONE, PLTRST, NF1),
	/* VGPIO_PCIE71 - VGPIO_PCIE71 */
	PAD_CFG_NF(VGPIO_PCIE71, NONE, PLTRST, NF1),
	/* VGPIO_PCIE72 - VGPIO_PCIE72 */
	PAD_CFG_NF(VGPIO_PCIE72, NONE, PLTRST, NF1),
	/* VGPIO_PCIE73 - VGPIO_PCIE73 */
	PAD_CFG_NF(VGPIO_PCIE73, NONE, PLTRST, NF1),
	/* VGPIO_PCIE74 - VGPIO_PCIE74 */
	PAD_CFG_NF(VGPIO_PCIE74, NONE, PLTRST, NF1),
	/* VGPIO_PCIE75 - VGPIO_PCIE75 */
	PAD_CFG_NF(VGPIO_PCIE75, NONE, PLTRST, NF1),
	/* VGPIO_PCIE76 - VGPIO_PCIE76 */
	PAD_CFG_NF(VGPIO_PCIE76, NONE, PLTRST, NF1),
	/* VGPIO_PCIE77 - VGPIO_PCIE77 */
	PAD_CFG_NF(VGPIO_PCIE77, NONE, PLTRST, NF1),
	/* VGPIO_PCIE78 - VGPIO_PCIE78 */
	PAD_CFG_NF(VGPIO_PCIE78, NONE, PLTRST, NF1),
	/* VGPIO_PCIE79 - VGPIO_PCIE79 */
	PAD_CFG_NF(VGPIO_PCIE79, NONE, PLTRST, NF1),

	/* ------- GPIO Group VGPIO_USB ------- */

	/* VGPIO_USB0 - VGPIO_USB0 */
	PAD_CFG_NF(VGPIO_USB0, NONE, DEEP, NF1),
	/* VGPIO_USB1 - VGPIO_USB1 */
	PAD_CFG_NF(VGPIO_USB1, NONE, DEEP, NF1),
	/* VGPIO_USB2 - VGPIO_USB2 */
	PAD_CFG_NF(VGPIO_USB2, NONE, DEEP, NF1),
	/* VGPIO_USB3 - VGPIO_USB3 */
	PAD_CFG_NF(VGPIO_USB3, NONE, DEEP, NF1),
	/* VGPIO_USB4 - VGPIO_USB4 */
	PAD_CFG_NF(VGPIO_USB4, NONE, DEEP, NF1),
	/* VGPIO_USB5 - VGPIO_USB5 */
	PAD_CFG_NF(VGPIO_USB5, NONE, DEEP, NF1),
	/* VGPIO_USB6 - VGPIO_USB6 */
	PAD_CFG_NF(VGPIO_USB6, NONE, DEEP, NF1),
	/* VGPIO_USB7 - VGPIO_USB7 */
	PAD_CFG_NF(VGPIO_USB7, NONE, DEEP, NF1),
	/* VGPIO_USB8 - VGPIO_USB8 */
	PAD_CFG_NF(VGPIO_USB8, NONE, DEEP, NF1),
	/* VGPIO_USB9 - VGPIO_USB9 */
	PAD_CFG_NF(VGPIO_USB9, NONE, DEEP, NF1),
	/* VGPIO_USB10 - VGPIO_USB10 */
	PAD_CFG_NF(VGPIO_USB10, NONE, DEEP, NF1),
	/* VGPIO_USB11 - VGPIO_USB11 */
	PAD_CFG_NF(VGPIO_USB11, NONE, DEEP, NF1),

	/* ------- GPIO Community 3 ------- */

	/* ------- GPIO Group GPD ------- */


	/* GPD0 - BATLOW# */
	PAD_CFG_NF(GPD0, NONE, PWROK, NF1),
	/* GPD1 - PMC_ACPRESENT */
	PAD_CFG_NF(GPD1, NATIVE, PWROK, NF1),
	/* GPD2 - LAN_WAKE# */
	PAD_CFG_NF(GPD2, NATIVE, PWROK, NF1),
	/* GPD3 - PWRBTN# */
	PAD_CFG_NF(GPD3, UP_20K, PWROK, NF1),
	/* GPD4 - SLP_S3# */
	PAD_CFG_NF(GPD4, NONE, PWROK, NF1),
	/* GPD5 - SLP_S4# */
	PAD_CFG_NF(GPD5, NONE, PWROK, NF1),
	/* GPD6 - SLP_A# */
	PAD_CFG_NF(GPD6, NONE, DEEP, NF1),
	/* GPD7 - GPIO */
	PAD_NC(GPD7, NONE),
	/* GPD8 - SUSCLK */
	PAD_CFG_NF(GPD8, NONE, PWROK, NF1),
	/* GPD9 - SLP_WLAN# */
	PAD_CFG_NF(GPD9, NONE, DEEP, NF1),
	/* GPD10 - SLP_S5# */
	PAD_CFG_NF(GPD10, NONE, DEEP, NF1),

	/* ------- GPIO Community 4 ------- */

	/* ------- GPIO Group GPP_H ------- */

	/* GPP_H00 - GPIO */
	PAD_NC(GPP_H00, NONE),
	/* GPP_H01 - GPIO */
	PAD_NC(GPP_H01, NONE),
	/* GPP_H02 - GPIO */
	PAD_NC(GPP_H02,NONE),
	/* GPP_H03 - GPIO */
	PAD_NC(GPP_H03, NONE),
	/* GPP_H04 - GPIO */
	PAD_NC(GPP_H04, NONE),
	/* GPP_H05 - GPIO */
	PAD_NC(GPP_H05, NONE),
	/* GPP_H06 - GPIO */
	PAD_NC(GPP_H06, NONE),
	/* GPP_H07 - GPIO */
	PAD_NC(GPP_H07, NONE),
	/* GPP_H08 - GPIO */
	PAD_NC(GPP_H08, NONE),
	/* GPP_H09 - GPIO */
	PAD_NC(GPP_H09, NONE),
	/* GPP_H10 - GPIO */
	PAD_NC(GPP_H10, NONE),
	/* GPP_H11 - GPIO */
	PAD_NC(GPP_H11,NONE),
	/* GPP_H12 - GPIO */
	PAD_NC(GPP_H12,NONE),
	/* GPP_H13 - GPIO */
	PAD_NC(GPP_H13,NONE),
	/* GPP_H14 - GPIO */
	PAD_NC(GPP_H14,NONE),
	/* GPP_H15 - GPIO */
	PAD_NC(GPP_H15, NONE),
	/* GPP_H16 - GPIO */
	PAD_NC(GPP_H16,NONE),
	/* GPP_H17 - GPIO */
	PAD_NC(GPP_H17, NONE),
	/* GPP_H18 - GPIO */
	PAD_NC(GPP_H18,NONE),
	/* GPP_H19 - GPIO */
	PAD_NC(GPP_H19,NONE),
	/* GPP_H20 - GPIO */
	PAD_NC(GPP_H20, NONE),
	/* GPP_H21 - GPIO */
	PAD_NC(GPP_H21, NONE),
	/* GPP_H22 - GPIO */
	PAD_NC(GPP_H22, NONE),
	/* GPP_H23 - GPIO */
	PAD_NC(GPP_H23, NONE),

	/* ------- GPIO Group GPP_D ------- */

	/* GPP_D00 - GPIO */
	PAD_NC(GPP_D00, NONE),
	/* GPP_D01 - GPIO */
	PAD_NC(GPP_D01, NONE),
	/* GPP_D02 - GPIO */
	PAD_NC(GPP_D02, NONE),
	/* GPP_D03 - GPIO */
	PAD_NC(GPP_D03, NONE),
	/* GPP_D04 - GPIO */
	PAD_NC(GPP_D04, NONE),
	/* GPP_D05 - GPIO */
	PAD_NC(GPP_D05, NONE),
	/* GPP_D06 - GPIO */
	PAD_NC(GPP_D06, NONE),
	/* GPP_D07 - GPIO */
	PAD_NC(GPP_D07, NONE),
	/* GPP_D08 - GPIO */
	PAD_NC(GPP_D08, NONE),
	/* GPP_D09 - GPIO */
	PAD_NC(GPP_D09, NONE),
	/* GPP_D10 - GPIO */
	PAD_NC(GPP_D10, NONE),
	/* GPP_D11 - GPIO */
	PAD_NC(GPP_D11, NONE),
	/* GPP_D12 - GPIO */
	PAD_NC(GPP_D12, NONE),
	/* GPP_D13 - GPIO */
	PAD_NC(GPP_D13, NONE),
	/* GPP_D14 - GPIO */
	PAD_NC(GPP_D14, NONE),
	/* GPP_D15 - GPIO */
	PAD_NC(GPP_D15, NONE),
	/* GPP_D16 - GPIO */
	PAD_NC(GPP_D16, NONE),
	/* GPP_D17 - GPIO */
	PAD_NC(GPP_D17, NONE),
	/* GPP_D18 - GPIO */
	PAD_NC(GPP_D18, NONE),
	/* GPP_D19 - GPIO */
	PAD_NC(GPP_D19, NONE),
	/* GPP_D20 - GPIO */
	PAD_NC(GPP_D20, NONE),
	/* GPP_D21 - GPIO */
	PAD_NC(GPP_D21, NONE),
	/* GPP_D22 - GPIO */
	PAD_NC(GPP_D22, NONE),
	/* GPP_D23 - GPIO */
	PAD_NC(GPP_D23, NONE),

	/* ------- GPIO Group VGPIO ------- */

	/* ------- GPIO Group GPP_C ------- */

	/* GPP_C00 - GPIO */
	PAD_NC(GPP_C00, NONE),
	/* GPP_C01 - GPIO */
	PAD_NC(GPP_C01, NONE),
	/* GPP_C02 - GPIO */
	PAD_NC(GPP_C02, NONE),
	/* GPP_C03 - GPIO */
	PAD_NC(GPP_C03, NONE),
	/* GPP_C04 - GPIO */
	PAD_NC(GPP_C04, NONE),
	/* GPP_C05 - GPIO */
	PAD_NC(GPP_C05, NONE),
	/* GPP_C06 - GPIO */
	PAD_CFG_GPO(GPP_C06, 1, DEEP),
	/* GPP_C07 - GPIO */
	PAD_NC(GPP_C07, NONE),
	/* GPP_C08 - GPIO */
	PAD_NC(GPP_C08, NONE)
	/* GPP_C09 - GPIO */
	PAD_NC(GPP_C09, NONE),
	/* GPP_C10 - GPIO */
	PAD_NC(GPP_C10, NONE),
	/* GPP_C11 - GPIO */
	PAD_NC(GPP_C11, NONE)
	/* GPP_C12 - GPIO */
	PAD_NC(GPP_C12, NONE)
	/* GPP_C13 - GPIO */
	PAD_NC(GPP_C13, NONE),
	/* GPP_C14 - GPIO */
	PAD_NC(GPP_C14, NONE),
	/* GPP_C15 - GPIO */
	PAD_NC(GPP_C15, NONE),
	/* GPP_C16 - GPIO */
	PAD_NC(GPP_C16, NONE),
	/* GPP_C17 - GPIO */
	PAD_NC(GPP_C17, NONE),
	/* GPP_C18 - GPIO */
	PAD_NC(GPP_C18, NONE),
	/* GPP_C19 - GPIO */
	PAD_NC(GPP_C19, NONE),
	/* GPP_C20 - GPIO */
	PAD_NC(GPP_C20, NONE),
	/* GPP_C21 - GPIO */
	PAD_NC(GPP_C21, NONE),
	/* GPP_C22 - GPIO */
	PAD_NC(GPP_C22, NONE),
	/* GPP_C23 - GPIO */
	PAD_NC(GPP_C23, NONE),

	/* ------- GPIO Community 5 ------- */

	/* ------- GPIO Group GPP_F ------- */

	/* GPP_F00 - GPIO */
	PAD_NC(GPP_F00, NONE),
	/* GPP_F01 - GPIO */
	PAD_NC(GPP_F01, NONE),
	/* GPP_F02 - GPIO */
	PAD_NC(GPP_F02, NONE),
	/* GPP_F03 - GPIO */
	PAD_NC(GPP_F03, NONE),
	/* GPP_F04 - GPIO */
	PAD_NC(GPP_F04, NONE),
	/* GPP_F05 - GPIO */
	PAD_NC(GPP_F05, NONE),
	/* GPP_F06 - GPIO */
	PAD_NC(GPP_F06, NONE),
	/* GPP_F07 - EMMC_CMD */
	PAD_CFG_NF(GPP_F07, NONE, DEEP, NF1),
	/* GPP_F08 - EMMC_DATA0 */
	PAD_CFG_NF(GPP_F08, NONE, DEEP, NF1),
	/* GPP_F09 - EMMC_DATA1 */
	PAD_CFG_NF(GPP_F09, NONE, DEEP, NF1),
	/* GPP_F10 - EMMC_DATA2 */
	PAD_CFG_NF(GPP_F10, NONE, DEEP, NF1),
	/* GPP_F11 - EMMC_DATA3 */
	PAD_CFG_NF(GPP_F11, NONE, DEEP, NF1),
	/* GPP_F12 - EMMC_DATA4 */
	PAD_CFG_NF(GPP_F12, NONE, DEEP, NF1),
	/* GPP_F13 - EMMC_DATA5 */
	PAD_CFG_NF(GPP_F13, NONE, DEEP, NF1),
	/* GPP_F14 - EMMC_DATA6 */
	PAD_CFG_NF(GPP_F14, NONE, DEEP, NF1),
	/* GPP_F15 - EMMC_DATA7 */
	PAD_CFG_NF(GPP_F15, NONE, DEEP, NF1),
	/* GPP_F16 - EMMC_RCLK */
	PAD_CFG_NF(GPP_F16, NONE, DEEP, NF1),
	/* GPP_F17 - EMMC_CLK */
	PAD_CFG_NF(GPP_F17, NONE, DEEP, NF1),
	/* GPP_F18 - EMMC_RESET_N */
	PAD_CFG_NF(GPP_F18, NONE, DEEP, NF1),
	/* GPP_F19 - GPIO */
	PAD_NC(GPP_F19, NONE),

	/* ------- GPIO Group SPI ------- */

	/* ------- GPIO Group GPP_B ------- */

	/* GPP_B00 - PMC_CORE_VID0 */
	PAD_CFG_NF(GPP_B00, NONE, DEEP, NF1),
	/* GPP_B01 - PMC_CORE_VID1 */
	PAD_CFG_NF(GPP_B01, NONE, DEEP, NF1),
	/* GPP_B02 - GPIO */
	PAD_NC(GPP_B02, NONE),
	/* GPP_B03 - GPIO */
	PAD_NC(GPP_B03, NONE),
	/* GPP_B04 - GPIO */
	PAD_NC(GPP_B04, NONE),
	/* GPP_B05 - GPIO */
	PAD_NC(GPP_B05, NONE),
	/* GPP_B06 - GPIO */
	PAD_NC(GPP_B06, NONE),
	/* GPP_B07 - GPIO */
	PAD_NC(GPP_B07, NONE),
	/* GPP_B08 - GPIO */
	PAD_NC(GPP_B08, NONE),
	/* GPP_B09 - GPIO */
	PAD_NC(GPP_B09, NONE),
	/* GPP_B10 - GPIO */
	PAD_NC(GPP_B10, NONE),
	/* GPP_B11 - GPIO */
	PAD_NC(GPP_B11, NONE),
	/* GPP_B12 - PMC_SLP_S0_N */
	PAD_CFG_NF(GPP_B12, NONE, DEEP, NF1),
	/* GPP_B13 - PMC_PLTRST_N */
	PAD_CFG_NF(GPP_B13, NONE, DEEP, NF1),
	/* GPP_B14 - SPKR */
	PAD_CFG_NF(GPP_B14, NONE, DEEP, NF1),
	/* GPP_B15 - GPIO */
	PAD_NC(GPP_B15, NONE),
	/* GPP_B16 - GPIO */
	PAD_NC(GPP_B16, NONE),
	/* GPP_B17 - GPIO */
	PAD_NC(GPP_B17, NONE),
	/* GPP_B18 - GPIO */
	PAD_NC(GPP_B18, NONE),
	/* GPP_B19 - GPIO */
	PAD_NC(GPP_B19, NONE),
	/* GPP_B20 - GPIO */
	PAD_NC(GPP_B20, NONE),
	/* GPP_B21 - GPIO */
	PAD_NC(GPP_B21, NONE),
	/* GPP_B22 - GPIO */
	PAD_NC(GPP_B22, NONE),
	/* GPP_B23 - DDI2_HPD */
	PAD_CFG_NF(GPP_B23, NONE, PLTRST, NF1),

	/* ------- GPIO Group GPP_A ------- */

	/* GPP_A00 - ESPI_IO_0 */
	PAD_CFG_NF(GPP_A00, UP_20K, DEEP, NF1),
	/* GPP_A01 - ESPI_IO_1 */
	PAD_CFG_NF(GPP_A01, UP_20K, DEEP, NF1),
	/* GPP_A02 - ESPI_IO_2 */
	PAD_CFG_NF(GPP_A02, UP_20K, DEEP, NF1),
	/* GPP_A03 - ESPI_IO_3 */
	PAD_CFG_NF(GPP_A03, UP_20K, DEEP, NF1),
	/* GPP_A04 - ESPI_CS_N */
	PAD_CFG_NF(GPP_A04, UP_20K, DEEP, NF1),
	/* GPP_A05 - ESPI_CLK */
	PAD_CFG_NF(GPP_A05, DN_20K, DEEP, NF1),
	/* GPP_A06 - ESPI_RESET_N */
	PAD_CFG_NF(GPP_A06, NONE, DEEP, NF1),
	/* GPP_A07 - SMB_CLK */
	PAD_CFG_NF(GPP_A07, NONE, DEEP, NF1),
	/* GPP_A08 - SMB_DATA */
	PAD_CFG_NF(GPP_A08, NONE, DEEP, NF1),
	/* GPP_A09 - GPIO */
	PAD_NC(GPP_A09, NONE),
	/* GPP_A10 - GPIO */
	PAD_NC(GPP_A10, NONE),
	/* GPP_A11 - GPIO */
	PAD_NC(GPP_A11, NONE),
	/* GPP_A12 - GPIO */
	PAD_NC(GPP_A12, NONE),
	/* GPP_A13 - GPIO */
	PAD_NC(GPP_A13, NONE),
	/* GPP_A14 - GPIO */
	PAD_NC(GPP_A14, NONE),
	/* GPP_A15 - GPIO */
	PAD_NC(GPP_A15, NONE),
	/* GPP_A16 - DDI1_HPD */
	PAD_CFG_NF(GPP_A16, NONE, PLTRST, NF1),
	/* GPP_A17 - DDI0_HPD */
	PAD_CFG_NF(GPP_A17, NONE, DEEP, NF1),
	/* GPP_A18 - GPIO */
	PAD_NC(GPP_A18, NONE),
	/* GPP_A19 - GPIO */
	PAD_NC(GPP_A19, NONE),

	/* ------- GPIO Group GPP_S ------- */

	/* GPP_S00 - GPIO */
	PAD_NC(GPP_S00, NONE),
	/* GPP_S01 - GPIO */
	PAD_NC(GPP_S01, NONE),
	/* GPP_S02 - GPIO */
	PAD_NC(GPP_S02, NONE),
	/* GPP_S03 - GPIO */
	PAD_NC(GPP_S03, NONE),
	/* GPP_S04 - GPIO */
	PAD_NC(GPP_S04, NONE),
	/* GPP_S05 - GPIO */
	PAD_NC(GPP_S05, NONE),
	/* GPP_S06 - GPIO */
	PAD_NC(GPP_S06, NONE),
	/* GPP_S07 - GPIO */
	PAD_NC(GPP_S07, NONE),

	/* ------- GPIO Group GPP_R ------- */

	/* GPP_R00 - HDA_BCLK */
	PAD_CFG_NF(GPP_R00, NONE, DEEP, NF1),
	/* GPP_R01 - HDA_SYNC */
	PAD_CFG_NF(GPP_R01, NATIVE, DEEP, NF1),
	/* GPP_R02 - HDA_SDO */
	PAD_CFG_NF(GPP_R02, NATIVE, DEEP, NF1),
	/* GPP_R03 - HDA_SDI0 */
	PAD_CFG_NF(GPP_R03, NATIVE, DEEP, NF1),
	/* GPP_R04 - HDA_RST_N */
	PAD_CFG_NF(GPP_R04, NONE, DEEP, NF1),
	/* GPP_R05 - GPIO */
	PAD_NC(GPP_R05, NONE),
	/* GPP_R06 - GPIO */
	PAD_NC(GPP_R06, NONE),
	/* GPP_R07 - GPIO */
	PAD_NC(GPP_R07, NONE),
};

#endif /* CFG_GPIO_H */
