#ifndef ISTEP_14_H
#define ISTEP_14_H

#include <cpu/power/scom.h>

#define PEC_PBCQHWCFG_REG (0x4010C00)
#define PEC_NESTTRC_REG (0x4010C03)
#define P9N2_PEC_ADDREXTMASK_REG (0x4010C05)
#define MCS_MCMODE0 (0x5010811)
#define MCS_MCSYNC (0x5010815)
#define MCA_MBA_FARB3Q (0x7010916)
#define PEC_PBAIBHWCFG_REG (0xD010800)

#define MCS_MCSYNC_SYNC_GO_CH0 (16)
#define SUPER_SYNC_BIT (14)
#define MBA_REFRESH_SYNC_BIT (8)
#define MCS_MCMODE0_DISABLE_MC_SYNC (27)
#define MCS_MCMODE0_DISABLE_MC_PAIR_SYNC (28)
#define PEC_PBAIBHWCFG_REG_PE_PCIE_CLK_TRACE_EN (30)
#define PEC_PBCQHWCFG_REG_PE_DISABLE_OOO_MODE (0x16)
#define PEC_PBCQHWCFG_REG_PE_DISABLE_WR_SCOPE_GROUP (42)
#define PEC_PBCQHWCFG_REG_PE_CHANNEL_STREAMING_EN (33)
#define PEC_PBCQHWCFG_REG_PE_DISABLE_WR_VG (41)
#define PEC_PBCQHWCFG_REG_PE_DISABLE_INTWR_VG (43)
#define PEC_PBCQHWCFG_REG_PE_DISABLE_INTWR_SCOPE_GROUP (44)
#define PEC_PBCQHWCFG_REG_PE_DISABLE_RD_SCOPE_GROUP (51)
#define PEC_PBCQHWCFG_REG_PE_DISABLE_RD_VG (54)
#define PEC_PBCQHWCFG_REG_PE_DISABLE_TCE_SCOPE_GROUP (56)
#define PEC_PBCQHWCFG_REG_PE_DISABLE_TCE_VG (59)

#define PEC_PER_PROC (3)
static const chiplet_id_t pec_ids[PEC_PER_PROC] = {
  PCI0_CHIPLET_ID, PCI1_CHIPLET_ID, PCI2_CHIPLET_ID,
};

void istep_14_2(void);
void istep_14_3(void);
#endif
