/* SPDX-License-Identifier: GPL-2.0-only */

#include <mainboard/gpio.h>
#include <soc/gpio.h>

static const struct pad_config gpio_table[] = {
	PAD_CFG_NF(GPP_A00, UP_20K, PLTRST, NF1), // ESPI_IO0
	PAD_CFG_NF(GPP_A01, UP_20K, PLTRST, NF1), // ESPI_IO1
	PAD_CFG_NF(GPP_A02, UP_20K, PLTRST, NF1), // ESPI_IO2
	PAD_CFG_NF(GPP_A03, UP_20K, PLTRST, NF1), // ESPI_IO3
	PAD_CFG_NF(GPP_A04, UP_20K, PLTRST, NF1), // ESPI_CS0#
	PAD_CFG_NF(GPP_A05, UP_20K, PLTRST, NF1), // ESPI_CLK
	PAD_CFG_NF(GPP_A06, NONE, PLTRST, NF1), // ESPI_RESET#
	PAD_NC(GPP_A07, NONE),
	PAD_NC(GPP_A08, NONE),
	PAD_NC(GPP_A09, NONE),
	PAD_NC(GPP_A10, NONE),
	PAD_CFG_GPI_TRIG_OWN(GPP_A11, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_A12, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_A13, UP_20K, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_A14, UP_20K, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_A15, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_NF(GPP_A16, UP_20K, PLTRST, NF1), // ESPI_ALERT0#
	PAD_CFG_GPI_TRIG_OWN(GPP_A17, UP_20K, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_A18, UP_20K, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_A19, UP_20K, DEEP, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_A20, NATIVE, DEEP, OFF, ACPI),
	PAD_CFG_NF(GPP_A21, NATIVE, DEEP, NF1), // PMCALERT#

	PAD_CFG_GPI_TRIG_OWN(GPP_B00, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_B01, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_B02, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_B03, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_B04, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_B05, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_B06, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_B07, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPO(GPP_B08, 1, PLTRST),
	PAD_CFG_GPI_TRIG_OWN(GPP_B09, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_B10, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_B11, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_B12, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_NF(GPP_B13, NONE, PLTRST, NF1), // PLTRST#
	PAD_CFG_GPI_TRIG_OWN(GPP_B14, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_B15, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_NF(GPP_B16, NONE, PLTRST, NF2), // HDMI_HPD2
	PAD_CFG_GPI_TRIG_OWN(GPP_B17, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPO(GPP_B18, 1, PLTRST),
	PAD_CFG_GPO(GPP_B19, 1, PLTRST),
	PAD_CFG_GPI_TRIG_OWN(GPP_B20, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_B21, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_B22, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_B23, NONE, PLTRST, OFF, ACPI),

	PAD_CFG_NF(GPP_C00, UP_20K, PLTRST, NF1), // SMBCLK
	PAD_CFG_NF(GPP_C01, UP_20K, PLTRST, NF1), // SMBDATA
	PAD_CFG_GPI_TRIG_OWN(GPP_C02, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_NF(GPP_C03, NONE, PLTRST, NF1), // SML0CLK
	PAD_CFG_NF(GPP_C04, NONE, PLTRST, NF1), // SML0DATA
	PAD_CFG_GPI_TRIG_OWN(GPP_C05, NONE, PLTRST, OFF, ACPI), // SM0ALERT#
	PAD_CFG_NF(GPP_C06, NONE, PLTRST, NF1), // SML1CLK
	PAD_CFG_NF(GPP_C07, NONE, PLTRST, NF1), // SML1DATA
	PAD_CFG_GPI_TRIG_OWN(GPP_C08, NONE, PLTRST, OFF, ACPI), // SML1ALERT#
	PAD_NC(GPP_C09, NONE),
	PAD_CFG_NF(GPP_C10, NONE, DEEP, NF1), // SRCCLKREQ1#
	PAD_CFG_NF(GPP_C11, NONE, DEEP, NF1), // SRCCLKREQ2#
	PAD_CFG_NF(GPP_C12, NONE, DEEP, NF1), // SRCCLKREQ3#
	PAD_NC(GPP_C13, NONE),
	PAD_NC(GPP_C14, NONE),
	PAD_CFG_GPI_TRIG_OWN(GPP_C15, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_NF(GPP_C16, NONE, DEEP, NF1), // TBT_LSX0_TXD
	PAD_CFG_NF(GPP_C17, NONE, DEEP, NF1), // TBT_LSX0_RXD
	PAD_CFG_GPI_TRIG_OWN(GPP_C18, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_C19, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_C20, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_C21, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_C22, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_C23, NONE, PLTRST, OFF, ACPI),

	PAD_CFG_GPO(GPP_D00, 0, RSMRST),
	PAD_CFG_GPI_TRIG_OWN(GPP_D01, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_D02, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_D03, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPO(GPP_D04, 1, RSMRST),
	PAD_CFG_GPO(GPP_D05, 1, PLTRST),
	PAD_CFG_GPO(GPP_D06, 1, PLTRST),
	PAD_CFG_GPO(GPP_D07, 1, PLTRST),
	PAD_CFG_GPO(GPP_D08, 1, PLTRST),
	PAD_CFG_GPO(GPP_D09, 0, RSMRST), // ME_OVERRIDE
	PAD_CFG_NF(GPP_D10, NONE, PLTRST, NF1), // HDA_BCLK
	PAD_CFG_NF(GPP_D11, NATIVE, PLTRST, NF1), // HDA_SYNC
	PAD_CFG_NF(GPP_D12, NATIVE, PLTRST, NF1), // HDA_SDO
	PAD_CFG_NF(GPP_D13, NATIVE, PLTRST, NF1), // HDA_SDI0
	PAD_CFG_GPI_TRIG_OWN(GPP_D14, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_D15, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_D16, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_NF(GPP_D17, NONE, PLTRST, NF1), // HDA_RST#
	PAD_CFG_NF(GPP_D18, NONE, DEEP, NF1), // SRCCLKREQ6#
	PAD_NC(GPP_D19, NONE),
	PAD_CFG_GPI_TRIG_OWN(GPP_D20, NONE, DEEP, OFF, ACPI), // SRCCLKREQ8#
	PAD_CFG_NF(GPP_D21, NONE, DEEP, NF1),
	PAD_CFG_GPI_TRIG_OWN(GPP_D22, NATIVE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_D23, NATIVE, PLTRST, OFF, ACPI),

	PAD_CFG_GPI_TRIG_OWN(GPP_E00, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_E01, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_E02, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_E03, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPO(GPP_E04, 0, PLTRST),
	PAD_CFG_GPO(GPP_E05, 1, PLTRST),
	PAD_CFG_GPI_TRIG_OWN(GPP_E06, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_E07, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_NF(GPP_E08, NONE, PLTRST, NF1), // DDPA_CTRLDATA
	PAD_CFG_GPI_TRIG_OWN(GPP_E09, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_E10, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_E11, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_E12, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_E13, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_NF(GPP_E14, NONE, PLTRST, NF1), // HDMI_HPD
	PAD_CFG_GPI_TRIG_OWN(GPP_E15, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_NF(GPP_E16, NONE, PLTRST, NF2), // VRALERT#
	PAD_CFG_GPI_TRIG_OWN(GPP_E17, NONE, PLTRST, OFF, ACPI),
	PAD_NC(GPP_E18, NONE),
	PAD_NC(GPP_E19, NONE),
	PAD_NC(GPP_E20, NONE),
	PAD_NC(GPP_E21, NONE),
	PAD_CFG_NF(GPP_E22, DN_20K, PLTRST, NF1), // DDPA_CTRLCLK

	PAD_CFG_NF(GPP_F00, NONE, PLTRST, NF1), // CNV_BRI_DT
	PAD_CFG_NF(GPP_F01, UP_20K, PLTRST, NF1), // CNV_BRI_RSP
	PAD_CFG_NF(GPP_F02, NONE, PLTRST, NF1), // CNV_BRI_RSP
	PAD_CFG_NF(GPP_F03, UP_20K, PLTRST, NF1), // CNV_RGI_DT
	PAD_CFG_NF(GPP_F04, NONE, PLTRST, NF1), // CNV_RGI_RSP
	PAD_CFG_NF(GPP_F05, NONE, PLTRST, NF3), // CNV_RF_RESET#
	PAD_CFG_NF(GPP_F06, NONE, PLTRST, NF1), // MODEM_CLKREQ
	PAD_CFG_TERM_GPO(GPP_F07, 1, DN_20K, RSMRST), // CNV_PA_BLANKING
	PAD_CFG_GPI_TRIG_OWN(GPP_F08, DN_20K, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_F09, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_F10, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_F11, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_F12, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_F13, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_F14, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_F15, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_F16, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_F17, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_F18, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_F19, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_F20, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_F21, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_F22, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_F23, NONE, PLTRST, OFF, ACPI),

	PAD_CFG_GPI_TRIG_OWN(GPP_H00, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_H01, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_H02, NONE, PLTRST, OFF, ACPI),
	PAD_NC(GPP_H03, NONE),
	PAD_CFG_NF(GPP_H04, NONE, PLTRST, NF2), // CNV_MFUART2_RXD
	PAD_CFG_NF(GPP_H05, NONE, PLTRST, NF2), // CNV_MFUART2_TXD
	PAD_CFG_GPI_TRIG_OWN(GPP_H06, UP_20K, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_H07, UP_20K, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_H08, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_H09, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_H10, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_H11, NONE, PLTRST, OFF, ACPI),
	PAD_NC(GPP_H12, NONE),
	PAD_CFG_GPI_TRIG_OWN(GPP_H13, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_H14, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPO(GPP_H15, 1, PLTRST),
	PAD_CFG_NF(GPP_H16, NONE, PLTRST, NF1), // DDPB_CTRLCLK
	PAD_CFG_NF(GPP_H17, NONE, PLTRST, NF1), // DDPB_CTRLDATA
	PAD_NC(GPP_H18, NONE),
	PAD_CFG_NF(GPP_H19, NONE, PLTRST, NF1), // CCG6DF_I2C_SDA (PD)
	PAD_CFG_NF(GPP_H20, NONE, PLTRST, NF1), // CCG6DF_I2C_SCL (PD)
	PAD_CFG_GPO(GPP_H21, 1, PLTRST),
	PAD_CFG_GPI_TRIG_OWN(GPP_H22, NONE, PLTRST, OFF, ACPI),

	PAD_CFG_GPI_TRIG_OWN(GPP_S00, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_S01, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_S02, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_S03, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_S04, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_S05, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_S06, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_S07, NONE, PLTRST, OFF, ACPI),

	PAD_CFG_NF(GPP_V00, UP_20K, PLTRST, NF1), // BATLOW#
	PAD_CFG_NF(GPP_V01, NATIVE, PLTRST, NF1), // ACPRESENT
	PAD_CFG_NF(GPP_V02, NATIVE, PLTRST, NF1), // SOC_WAKE#
	PAD_CFG_NF(GPP_V03, UP_20K, PLTRST, NF1), // PWRBTN#
	PAD_CFG_NF(GPP_V04, NONE, PLTRST, NF1), // SLP_S3#
	PAD_CFG_NF(GPP_V05, NONE, PLTRST, NF1), // SLP_S4#
	PAD_CFG_GPI_TRIG_OWN(GPP_V06, NONE, PLTRST, OFF, ACPI),
	PAD_NC(GPP_V07, NONE),
	PAD_CFG_NF(GPP_V08, NONE, PLTRST, NF1), // SUSCLK
	PAD_CFG_GPI_TRIG_OWN(GPP_V09, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_V10, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_V11, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_V12, NONE, PLTRST, OFF, ACPI),
	PAD_NC(GPP_V13, NONE),
	PAD_CFG_NF(GPP_V14, NONE, PLTRST, NF1), // WAKE#
	PAD_NC(GPP_V15, NONE),
	PAD_NC(GPP_V16, NONE),
	PAD_NC(GPP_V17, NONE),
	PAD_NC(GPP_V18, NONE),
	PAD_CFG_NF(GPP_V19, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_V20, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_V21, NONE, DEEP, NF1),
	PAD_CFG_GPI_TRIG_OWN(GPP_V22, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_V23, NONE, PLTRST, OFF, ACPI),
};

void mainboard_configure_gpios(void)
{
	gpio_configure_pads(gpio_table, ARRAY_SIZE(gpio_table));
}
