name: check-upstream-status

on:
  pull_request:

jobs:
  check-upstream-status:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Checkout pull request HEAD commit instead of merge commit
        # See: https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: check-upstream-status --hook-stage pre-push
