/* SPDX-License-Identifier: GPL-2.0-only */

#include <gpio.h>

#include "gpio.h"

#ifndef PAD_CFG_GPIO_BIDIRECT
#define PAD_CFG_GPIO_BIDIRECT(pad, val, pull, rst, trig, own)		\
	_PAD_CFG_STRUCT(pad,						\
		PAD_FUNC(GPIO) | PAD_RESET(rst) | PAD_TRIG(trig) |	\
		PAD_BUF(NO_DISABLE) | val,				\
		PAD_PULL(pull) | PAD_CFG_OWN_GPIO(own))
#endif

/* Pad configuration was generated automatically using intelp2m utility */
static const struct pad_config gpio_table[] = {

	/* ------- GPIO Community 0 ------- */

	/* ------- GPIO Group GPP_B ------- */

	/* GPP_B0 - CORE_VID0 */
	PAD_CFG_NF(GPP_B0, NONE, DEEP, NF1),
	/* GPP_B1 - CORE_VID1 */
	PAD_CFG_NF(GPP_B1, NONE, DEEP, NF1),
	/* GPP_B2 - VRALERT# */
	PAD_CFG_NF(GPP_B2, NONE, DEEP, NF1),
	/* GPP_B3 - GPIO */
	PAD_NC(GPP_B3, NONE),
	/* GPP_B4 - GPIO */
	PAD_NC(GPP_B4, NONE),
	/* GPP_B5 - GPIO */
	PAD_NC(GPP_B5, NONE),
	/* GPP_B6 - GPIO */
	PAD_NC(GPP_B6, NONE),
	/* GPP_B7 - GPIO */
	PAD_NC(GPP_B7, NONE),
	/* GPP_B8 - GPIO EMMC_DET# */
	PAD_CFG_GPI(GPP_B8, UP_20K, PLTRST),
	/* GPP_B9 - GPIO */
	PAD_NC(GPP_B9, NONE),
	/* GPP_B10 - GPIO */
	PAD_NC(GPP_B10, NONE),
	/* GPP_B11 - PMCALERT# */
	PAD_CFG_NF(GPP_B11, NONE, DEEP, NF1),
	/* GPP_B12 - SLP_S0# */
	PAD_CFG_NF(GPP_B12, NONE, DEEP, NF1),
	/* GPP_B13 - PLTRST# */
	PAD_CFG_NF(GPP_B13, NONE, DEEP, NF1),
	/* GPP_B14 - SATA_LED# */
	PAD_CFG_NF(GPP_B14, NONE, DEEP, NF4),
	/* GPP_B15 - GPIO */
	PAD_NC(GPP_B15, NONE),
	/* GPP_B16 - GPIO */
	PAD_NC(GPP_B16, NONE),
	/* GPP_B17 - GPIO */
	PAD_NC(GPP_B17, NONE),
	/* GPP_B18 - GPIO */
	PAD_NC(GPP_B18, NONE),
	/* GPP_B19 - GPIO */
	PAD_NC(GPP_B19, NONE),
	/* GPP_B20 - GPIO */
	PAD_NC(GPP_B20, NONE),
	/* GPP_B21 - GPIO */
	PAD_NC(GPP_B21, NONE),
	/* GPP_B22 - GPIO */
	PAD_NC(GPP_B22, NONE),
	/* GPP_B23 - GPIO */
	PAD_NC(GPP_B23, NONE),
	/* GPP_B24 - GSPI0_CLK_LOOPBK */
	PAD_CFG_NF(GPP_B24, NONE, DEEP, NF1),
	/* GPP_B25 - GSPI1_CLK_LOOPBK */
	PAD_CFG_NF(GPP_B25, NONE, DEEP, NF1),

	/* ------- GPIO Group GPP_T ------- */

	/* GPP_T0 - GPIO */
	PAD_NC(GPP_T0, NONE),
	/* GPP_T1 - GPIO */
	PAD_NC(GPP_T1, NONE),
	/* GPP_T2 - GPIO */
	PAD_NC(GPP_T2, NONE),
	/* GPP_T3 - GPIO */
	PAD_NC(GPP_T3, NONE),
	/* GPP_T4 - GPIO */
	PAD_NC(GPP_T4, NONE),
	/* GPP_T5 - GPIO */
	PAD_NC(GPP_T5, NONE),
	/* GPP_T6 - GPIO */
	PAD_NC(GPP_T6, NONE),
	/* GPP_T7 - GPIO */
	PAD_NC(GPP_T7, NONE),
	/* GPP_T8 - GPIO */
	PAD_NC(GPP_T8, NONE),
	/* GPP_T9 - GPIO */
	PAD_NC(GPP_T9, NONE),
	/* GPP_T10 - GPIO */
	PAD_NC(GPP_T10, NONE),
	/* GPP_T11 - GPIO */
	PAD_NC(GPP_T11, NONE),
	/* GPP_T12 - GPIO */
	PAD_NC(GPP_T12, NONE),
	/* GPP_T13 - GPIO */
	PAD_NC(GPP_T13, NONE),
	/* GPP_T14 - GPIO */
	PAD_NC(GPP_T14, NONE),
	/* GPP_T15 - GPIO */
	PAD_NC(GPP_T15, NONE),

	/* ------- GPIO Group GPP_A ------- */

	/* GPP_A0 - ESPI_IO0 */
	PAD_CFG_NF(GPP_A0, UP_20K, DEEP, NF1),
	/* GPP_A1 - ESPI_IO1 */
	PAD_CFG_NF(GPP_A1, UP_20K, DEEP, NF1),
	/* GPP_A2 - ESPI_IO2 */
	PAD_CFG_NF(GPP_A2, UP_20K, DEEP, NF1),
	/* GPP_A3 - ESPI_IO3 */
	PAD_CFG_NF(GPP_A3, UP_20K, DEEP, NF1),
	/* GPP_A4 - ESPI_CS0# */
	PAD_CFG_NF(GPP_A4, UP_20K, DEEP, NF1),
	/* GPP_A5 - ESPI_ALERT0# */
	PAD_CFG_NF(GPP_A5, UP_20K, DEEP, NF1),
	/* GPP_A6 - GPIO */
	PAD_NC(GPP_A6, NONE),
	/* GPP_A7 - GPIO */
	PAD_NC(GPP_A7, NONE),
	/* GPP_A8 - LAN_DISABLE# */
	PAD_CFG_GPO(GPP_VGPIO_0, 1, DEEP),
	/* GPP_A9 - ESPI_CLK */
	PAD_CFG_NF(GPP_A9, DN_20K, DEEP, NF1),
	/* GPP_A10 - ESPI_RESET# */
	PAD_CFG_NF(GPP_A10, NONE, DEEP, NF1),
	/* GPP_A11 - GPIO */
	PAD_NC(GPP_A11, NONE),
	/* GPP_A12 - SATAXPCIE1 */
	PAD_CFG_NF(GPP_A12, NONE, DEEP, NF1),
	/* GPP_A13 - GPIO */
	PAD_NC(GPP_A13, NONE),
	/* GPP_A14 - GPIO */
	PAD_NC(GPP_A14, NONE),
	/* GPP_A15 - GPIO */
	PAD_NC(GPP_A15, NONE),
	/* GPP_A16 - GPIO */
	PAD_NC(GPP_A16, NONE),
	/* GPP_A17 - GPIO */
	PAD_NC(GPP_A17, NONE),
	/* GPP_A18 - DDSP_HPDB */
	PAD_CFG_NF(GPP_A18, NONE, DEEP, NF1),
	/* GPP_A19 - DDSP_HPD1 */
	PAD_CFG_NF(GPP_A19, NONE, DEEP, NF1),
	/* GPP_A20 - GPIO */
	PAD_NC(GPP_A20, NONE),
	/* GPP_A21 - GPIO */
	PAD_NC(GPP_A21, NONE),
	/* GPP_A22 - GPIO */
	PAD_NC(GPP_A22, NONE),
	/* GPP_A23 - GPIO */
	PAD_NC(GPP_A23, NONE),
	/* GPP_ESPI_CLK_LOOPBK - GPP_ESPI_CLK_LOOPBK */
	PAD_CFG_NF(GPP_ESPI_CLK_LOOPBK, NONE, DEEP, NF1),

	/* ------- GPIO Community 1 ------- */

	/* ------- GPIO Group GPP_S ------- */

	/* GPP_S0 - GPIO */
	PAD_NC(GPP_S0, NONE),
	/* GPP_S1 - GPIO */
	PAD_NC(GPP_S1, NONE),
	/* GPP_S2 - GPIO */
	PAD_NC(GPP_S2, NONE),
	/* GPP_S3 - GPIO */
	PAD_NC(GPP_S3, NONE),
	/* GPP_S4 - GPIO */
	PAD_NC(GPP_S4, NONE),
	/* GPP_S5 - GPIO */
	PAD_NC(GPP_S5, NONE),
	/* GPP_S6 - GPIO */
	PAD_NC(GPP_S6, NONE),
	/* GPP_S7 - GPIO */
	PAD_NC(GPP_S7, NONE),

	/* ------- GPIO Group GPP_I ------- */

	/* GPP_I5 - GPIO */
	PAD_NC(GPP_I5, NONE),
	/* GPP_I7 - EMMC_CMD */
	PAD_CFG_NF(GPP_I7, NONE, DEEP, NF1),
	/* GPP_I8 - EMMC_DATA0 */
	PAD_CFG_NF(GPP_I8, NONE, DEEP, NF1),
	/* GPP_I9 - EMMC_DATA1 */
	PAD_CFG_NF(GPP_I9, NONE, DEEP, NF1),
	/* GPP_I10 - EMMC_DATA2 */
	PAD_CFG_NF(GPP_I10, NONE, DEEP, NF1),
	/* GPP_I11 - EMMC_DATA3 */
	PAD_CFG_NF(GPP_I11, NONE, DEEP, NF1),
	/* GPP_I12 - EMMC_DATA4 */
	PAD_CFG_NF(GPP_I12, NONE, DEEP, NF1),
	/* GPP_I13 - EMMC_DATA5 */
	PAD_CFG_NF(GPP_I13, NONE, DEEP, NF1),
	/* GPP_I14 - EMMC_DATA6 */
	PAD_CFG_NF(GPP_I14, NONE, DEEP, NF1),
	/* GPP_I15 - EMMC_DATA7 */
	PAD_CFG_NF(GPP_I15, NONE, DEEP, NF1),
	/* GPP_I16 - EMMC_RCLK */
	PAD_CFG_NF(GPP_I16, NONE, DEEP, NF1),
	/* GPP_I17 - EMMC_CLK */
	PAD_CFG_NF(GPP_I17, NONE, DEEP, NF1),
	/* GPP_I18 - EMMC_RESET# */
	PAD_CFG_NF(GPP_I18, NONE, DEEP, NF1),

	/* ------- GPIO Group GPP_H ------- */

	/* GPP_H0 - GPIO */
	PAD_NC(GPP_H0, NONE),
	/* GPP_H1 - GPIO */
	PAD_NC(GPP_H1, NONE),
	/* GPP_H2 - GPIO */
	PAD_NC(GPP_H2, NONE),
	/* GPP_H3 - GPIO */
	PAD_NC(GPP_H3, NONE),
	/* GPP_H4 - I2C0_SDA */
	PAD_CFG_NF(GPP_H4, NONE, DEEP, NF1),
	/* GPP_H5 - I2C0_SCL */
	PAD_CFG_NF(GPP_H5, NONE, DEEP, NF1),
	/* GPP_H6 - I2C1_SDA */
	PAD_CFG_NF(GPP_H6, NONE, DEEP, NF1),
	/* GPP_H7 - I2C1_SCL */
	PAD_CFG_NF(GPP_H7, NONE, DEEP, NF1),
	/* GPP_H8 - GPIO */
	PAD_NC(GPP_H8, NONE),
	/* GPP_H9 - GPIO */
	PAD_NC(GPP_H9, NONE),
	/* GPP_H10 - GPIO */
	PAD_NC(GPP_H10, NONE),
	/* GPP_H11 - GPIO */
	PAD_NC(GPP_H11, NONE),
	/* GPP_H12 - GPIO */
	PAD_NC(GPP_H12, NONE),
	/* GPP_H13 - GPIO */
	PAD_NC(GPP_H13, NONE),
	/* GPP_H14 - GPIO */
	PAD_NC(GPP_H14, NONE),
	/* GPP_H15 - DDPB_CTRLCLK */
	PAD_CFG_NF(GPP_H15, NONE, DEEP, NF1),
	/* GPP_H16 - GPIO */
	PAD_NC(GPP_H16, NONE),
	/* GPP_H17 - DDPB_CTRLDATA */
	PAD_CFG_NF(GPP_H17, NONE, DEEP, NF1),
	/* GPP_H18 - PROC_C10_GATE# */
	PAD_CFG_NF(GPP_H18, NONE, DEEP, NF1),
	/* GPP_H19 - GPIO */
	PAD_NC(GPP_H19, NONE),
	/* GPP_H20 - GPIO */
	PAD_NC(GPP_H20, NONE),
	/* GPP_H21 - GPIO */
	PAD_NC(GPP_H21, NONE),
	/* GPP_H22 - GPIO */
	PAD_NC(GPP_H22, NONE),
	/* GPP_H23 - GPIO */
	PAD_NC(GPP_H23, NONE),

	/* ------- GPIO Group GPP_D ------- */

	/* GPP_D0 - GPIO */
	PAD_NC(GPP_D0, NONE),
	/* GPP_D1 - GPIO */
	PAD_NC(GPP_D1, NONE),
	/* GPP_D2 - GPIO */
	PAD_NC(GPP_D2, NONE),
	/* GPP_D3 - GPIO */
	PAD_NC(GPP_D3, NONE),
	/* GPP_D4 - GPIO */
	PAD_NC(GPP_D4, NONE),
	/* GPP_D5 - SRCCLKREQ0# to PCIE RP 9 (NVMe) */
	PAD_CFG_NF(GPP_D5, NONE, DEEP, NF1),
	/* GPP_D6 - SRCCLKREQ1# to PCIE RP 3 (LAN1) */
	PAD_CFG_NF(GPP_D6, NONE, DEEP, NF1),
	/* GPP_D7 - SRCCLKREQ2# to PCIE RP 4 (LAN2) */
	PAD_CFG_NF(GPP_D7, NONE, DEEP, NF1),
	/* GPP_D8 - SRCCLKREQ3# presumably for PCIE RP7, but permanently grounded? */
	PAD_CFG_NF(GPP_D8, NONE, DEEP, NF1),
	/* GPP_D9 - GPIO */
	PAD_NC(GPP_D9, NATIVE),
	/* GPP_D10 - GPIO */
	PAD_NC(GPP_D10, NATIVE),
	/* GPP_D11 - GPIO */
	PAD_NC(GPP_D11, NATIVE),
	/* GPP_D12 - GPIO */
	PAD_NC(GPP_D12, NATIVE),
	/* GPP_D13 - GPIO */
	PAD_NC(GPP_D13, NONE),
	/* GPP_D14 - GPIO */
	PAD_NC(GPP_D14, NONE),
	/* GPP_D15 - GPIO */
	PAD_NC(GPP_D15, NONE),
	/* GPP_D16 - GPIO */
	PAD_NC(GPP_D16, NONE),
	/* GPP_D17 - GPIO */
	PAD_NC(GPP_D17, NONE),
	/* GPP_D18 - GPIO */
	PAD_NC(GPP_D18, NONE),
	/* GPP_D19 - GPIO */
	PAD_NC(GPP_D19, NONE),
	/* GPP_GSPI2_CLK_LOOPBK - GPP_GSPI2_CLK_LOOPBK */
	PAD_CFG_NF(GPP_GSPI2_CLK_LOOPBK, NONE, DEEP, NF1),

	/* ------- GPIO Group vGPIO ------- */

	/* GPP_VGPIO_0 - GPIO */
	PAD_CFG_GPO(GPP_VGPIO_0, 0, DEEP),
	/* GPP_VGPIO_4 - GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_VGPIO_4, NONE, DEEP, OFF, ACPI),
	/* GPP_VGPIO_5 - GPIO */
	PAD_CFG_GPIO_BIDIRECT(GPP_VGPIO_5, 1, NONE, DEEP, LEVEL, ACPI),
	/* GPP_VGPIO_6 - GPP_VGPIO_6 */
	PAD_CFG_NF(GPP_VGPIO_6, NONE, DEEP, NF1),
	/* GPP_VGPIO_7 - GPP_VGPIO_7 */
	PAD_CFG_NF(GPP_VGPIO_7, NONE, DEEP, NF1),
	/* GPP_VGPIO_8 - GPP_VGPIO_8 */
	PAD_CFG_NF(GPP_VGPIO_8, NONE, DEEP, NF1),
	/* GPP_VGPIO_9 - GPP_VGPIO_9 */
	PAD_CFG_NF(GPP_VGPIO_9, NONE, DEEP, NF1),
	/* GPP_VGPIO_10 - GPP_VGPIO_10 */
	PAD_CFG_NF(GPP_VGPIO_10, NONE, DEEP, NF1),
	/* GPP_VGPIO_11 - GPP_VGPIO_11 */
	PAD_CFG_NF(GPP_VGPIO_11, NONE, DEEP, NF1),
	/* GPP_VGPIO_12 - GPP_VGPIO_12 */
	PAD_CFG_NF(GPP_VGPIO_12, NONE, DEEP, NF1),
	/* GPP_VGPIO_13 - GPP_VGPIO_13 */
	PAD_CFG_NF(GPP_VGPIO_13, NONE, DEEP, NF1),
	/* GPP_VGPIO_18 - GPP_VGPIO_18 */
	PAD_CFG_NF(GPP_VGPIO_18, NONE, DEEP, NF1),
	/* GPP_VGPIO_19 - GPP_VGPIO_19 */
	PAD_CFG_NF(GPP_VGPIO_19, NONE, DEEP, NF1),
	/* GPP_VGPIO_20 - GPP_VGPIO_20 */
	PAD_CFG_NF(GPP_VGPIO_20, NONE, DEEP, NF1),
	/* GPP_VGPIO_21 - GPP_VGPIO_21 */
	PAD_CFG_NF(GPP_VGPIO_21, NONE, DEEP, NF1),
	/* GPP_VGPIO_22 - GPP_VGPIO_22 */
	PAD_CFG_NF(GPP_VGPIO_22, NONE, DEEP, NF1),
	/* GPP_VGPIO_23 - GPP_VGPIO_23 */
	PAD_CFG_NF(GPP_VGPIO_23, NONE, DEEP, NF1),
	/* GPP_VGPIO_24 - GPP_VGPIO_24 */
	PAD_CFG_NF(GPP_VGPIO_24, NONE, DEEP, NF1),
	/* GPP_VGPIO_25 - GPP_VGPIO_25 */
	PAD_CFG_NF(GPP_VGPIO_25, NONE, DEEP, NF1),
	/* GPP_VGPIO_30 - GPP_VGPIO_30 */
	PAD_CFG_NF(GPP_VGPIO_30, NONE, DEEP, NF1),
	/* GPP_VGPIO_31 - GPP_VGPIO_31 */
	PAD_CFG_NF(GPP_VGPIO_31, NONE, DEEP, NF1),
	/* GPP_VGPIO_32 - GPP_VGPIO_32 */
	PAD_CFG_NF(GPP_VGPIO_32, NONE, DEEP, NF1),
	/* GPP_VGPIO_33 - GPP_VGPIO_33 */
	PAD_CFG_NF(GPP_VGPIO_33, NONE, DEEP, NF1),
	/* GPP_VGPIO_34 - GPP_VGPIO_34 */
	PAD_CFG_NF(GPP_VGPIO_34, NONE, DEEP, NF1),
	/* GPP_VGPIO_35 - GPP_VGPIO_35 */
	PAD_CFG_NF(GPP_VGPIO_35, NONE, DEEP, NF1),
	/* GPP_VGPIO_36 - GPP_VGPIO_36 */
	PAD_CFG_NF(GPP_VGPIO_36, NONE, DEEP, NF1),
	/* GPP_VGPIO_37 - GPP_VGPIO_37 */
	PAD_CFG_NF(GPP_VGPIO_37, NONE, DEEP, NF1),
	/* GPP_VGPIO_THC0 - GPP_VGPIO_THC0 */
	PAD_CFG_NF(GPP_VGPIO_THC0, NONE, DEEP, NF1),
	/* GPP_VGPIO_THC1 - GPP_VGPIO_THC1 */
	PAD_CFG_NF(GPP_VGPIO_THC1, NONE, DEEP, NF1),

	/* ------- GPIO Community 2 ------- */

	/* ------- GPIO Group GPP_GPD ------- */

	/* GPD0 - BATLOW# */
	PAD_CFG_NF(GPD0, UP_20K, PWROK, NF1),
	/* GPD1 - ACPRESENT */
	PAD_CFG_NF(GPD1, NATIVE, PWROK, NF1),
	/* GPD2 - GPIO */
	PAD_NC(GPD2, NONE),
	/* GPD3 - PWRBTN# */
	PAD_CFG_NF(GPD3, UP_20K, PWROK, NF1),
	/* GPD4 - SLP_S3# */
	PAD_CFG_NF(GPD4, NONE, PWROK, NF1),
	/* GPD5 - SLP_S4# */
	PAD_CFG_NF(GPD5, NONE, PWROK, NF1),
	/* GPD6 - SLP_A# */
	PAD_CFG_NF(GPD6, NONE, PWROK, NF1),
	/* GPD7 - GPIO */
	PAD_NC(GPD7, NONE),
	/* GPD8 - SUS_CLK */
	PAD_CFG_NF(GPD8, NONE, PWROK, NF1),
	/* GPD9 - SLP_WLAN# */
	PAD_CFG_NF(GPD9, NONE, PWROK, NF1),
	/* GPD10 - SLP_S5# */
	PAD_CFG_NF(GPD10, NONE, PWROK, NF1),
	/* GPD11 - GPIO */
	PAD_NC(GPD11, NONE),
	/* GPD_INPUT3VSEL - GPD_INPUT3VSEL */
	PAD_CFG_NF(GPD_INPUT3VSEL, NONE, PWROK, NF1),
	/* GPD_SLP_LANB - GPD_SLP_LANB */
	PAD_CFG_NF(GPD_SLP_LANB, NONE, PWROK, NF1),
	/* GPD_SLP_SUSB - GPD_SLP_SUSB */
	PAD_CFG_NF(GPD_SLP_SUSB, NONE, PWROK, NF1),
	/* GPD_WAKEB - GPD_WAKEB */
	PAD_CFG_NF(GPD_WAKEB, NONE, PWROK, NF1),
	/* GPD_DRAM_RESETB - GPD_DRAM_RESETB */
	PAD_CFG_NF(GPD_DRAM_RESETB, NONE, PWROK, NF1),

	/* ------- GPIO Community 4 ------- */

	/* ------- GPIO Group GPP_C ------- */

	/* GPP_C0 - SMBCLK */
	PAD_CFG_NF(GPP_C0, NONE, DEEP, NF1),
	/* GPP_C1 - SMBDATA */
	PAD_CFG_NF(GPP_C1, NONE, DEEP, NF1),
	/* GPP_C2 - GPIO */
	PAD_NC(GPP_C2, NONE),
	/* GPP_C3 - GPIO */
	PAD_NC(GPP_C3, NONE),
	/* GPP_C4 - GPIO */
	PAD_NC(GPP_C4, NONE),
	/* GPP_C5 - GPIO */
	PAD_NC(GPP_C5, NONE),
	/* GPP_C6 - GPIO */
	PAD_NC(GPP_C6, NONE),
	/* GPP_C7 - GPIO */
	PAD_NC(GPP_C7, NONE),
	/* GPP_C8 - GPIO */
	PAD_NC(GPP_C8, NONE),
	/* GPP_C9 - GPIO */
	PAD_NC(GPP_C9, NONE),
	/* GPP_C10 - GPIO */
	PAD_NC(GPP_C10, NONE),
	/* GPP_C11 - GPIO */
	PAD_NC(GPP_C11, NONE),
	/* GPP_C12 - GPIO */
	PAD_NC(GPP_C12, NONE),
	/* GPP_C13 - GPIO */
	PAD_NC(GPP_C13, NONE),
	/* GPP_C14 - GPIO */
	PAD_NC(GPP_C14, NONE),
	/* GPP_C15 - GPIO */
	PAD_NC(GPP_C15, NONE),
	/* GPP_C16 - GPIO */
	PAD_NC(GPP_C16, NONE),
	/* GPP_C17 - GPIO */
	PAD_NC(GPP_C17, NONE),
	/* GPP_C18 - GPIO */
	PAD_NC(GPP_C18, NONE),
	/* GPP_C19 - GPIO */
	PAD_NC(GPP_C19, NONE),
	/* GPP_C20 - GPIO */
	PAD_NC(GPP_C20, NONE),
	/* GPP_C21 - GPIO */
	PAD_NC(GPP_C21, NONE),
	/* GPP_C22 - GPIO */
	PAD_NC(GPP_C22, NONE),
	/* GPP_C23 - GPIO */
	PAD_NC(GPP_C23, NONE),

	/* ------- GPIO Group GPP_F ------- */

	/* GPP_F0 - GPIO */
	PAD_NC(GPP_F0, NONE),
	/* GPP_F1 - GPIO */
	PAD_NC(GPP_F1, NONE),
	/* GPP_F2 - GPIO */
	PAD_NC(GPP_F2, NONE),
	/* GPP_F3 - GPIO */
	PAD_NC(GPP_F3, NONE),
	/* GPP_F4 - GPIO# */
	PAD_NC(GPP_F4, NONE),
	/* GPP_F5 - GPIO */
	PAD_NC(GPP_F5, NONE),
	/* GPP_F6 - GPIO */
	PAD_NC(GPP_F6, NONE),
	/* GPP_F7 - GPIO */
	PAD_NC(GPP_F7, NONE),
	/* GPP_F8 - GPIO */
	PAD_NC(GPP_F8, NONE),
	/* GPP_F9 - GPIO */
	PAD_NC(GPP_F9, NONE),
	/* GPP_F10 - GPIO */
	PAD_NC(GPP_F10, NONE),
	/* GPP_F11 - GPIO */
	PAD_NC(GPP_F11, NONE),
	/* GPP_F12 - GPIO */
	PAD_NC(GPP_F12, NONE),
	/* GPP_F13 - GPIO */
	PAD_NC(GPP_F13, NONE),
	/* GPP_F14 - GPIO */
	PAD_NC(GPP_F14, NONE),
	/* GPP_F15 - GPIO */
	PAD_NC(GPP_F15, NONE),
	/* GPP_F16 - GPIO */
	PAD_NC(GPP_F16, NONE),
	/* GPP_F17 - GPIO */
	PAD_NC(GPP_F17, NONE),
	/* GPP_F18 - GPIO */
	PAD_NC(GPP_F18, NONE),
	/* GPP_F19 - GPIO */
	PAD_NC(GPP_F19, NONE),
	/* GPP_F20 - Reserved */
	PAD_NC(GPP_F20, NONE),
	/* GPP_F21 - Reserved */
	PAD_NC(GPP_F21, NONE),
	/* GPP_F22 - GPIO */
	PAD_NC(GPP_F22, NONE),
	/* GPP_F23 - GPIO */
	PAD_NC(GPP_F23, NONE),
	/* GPP_F_CLK_LOOPBK - GPIO */
	PAD_NC(GPP_F_CLK_LOOPBK, NONE),

	/* ------- GPIO Group GPP_HVCMOS ------- */

	/* GPP_L_BKLTEN - n/a */
	PAD_NC(GPP_L_BKLTEN, NONE),
	/* GPP_L_BKLTCTL - n/a */
	PAD_NC(GPP_L_BKLTCTL, NONE),
	/* GPP_L_VDDEN - n/a */
	PAD_NC(GPP_L_VDDEN, NONE),
	/* GPP_SYS_PWROK - n/a */
	PAD_CFG_NF(GPP_SYS_PWROK, NONE, DEEP, NF1),
	/* GPP_SYS_RESETB - n/a */
	PAD_CFG_NF(GPP_SYS_RESETB, NONE, DEEP, NF1),
	/* GPP_MLK_RSTB - n/a */
	PAD_CFG_NF(GPP_MLK_RSTB, NONE, DEEP, NF1),

	/* ------- GPIO Group GPP_E ------- */

	/* GPP_E0 - GPIO */
	PAD_NC(GPP_E0, NONE),
	/* GPP_E1 - GPIO */
	PAD_NC(GPP_E1, NONE),
	/* GPP_E2 - GPIO */
	PAD_NC(GPP_E2, NONE),
	/* GPP_E3 - GPIO */
	PAD_NC(GPP_E3, NONE),
	/* GPP_E4 - GPIO */
	PAD_NC(GPP_E4, NONE),
	/* GPP_E5 - GPIO */
	PAD_NC(GPP_E5, NONE),
	/* GPP_E6 - GPIO */
	PAD_NC(GPP_E6, NONE),
	/* GPP_E7 - GPIO */
	PAD_NC(GPP_E7, NONE),
	/* GPP_E8 - GPIO */
	PAD_NC(GPP_E8, NONE),
	/* GPP_E9 - GPIO */
	PAD_NC(GPP_E9, NONE),
	/* GPP_E10 - GPIO */
	PAD_NC(GPP_E10, NONE),
	/* GPP_E11 - GPIO */
	PAD_NC(GPP_E11, NONE),
	/* GPP_E12 - GPIO */
	PAD_NC(GPP_E12, NONE),
	/* GPP_E13 - GPIO */
	PAD_NC(GPP_E13, NONE),
	/* GPP_E14 - DDSP_HPDA */
	PAD_CFG_NF(GPP_E14, NONE, DEEP, NF1),
	/* GPP_E15 - Reserved */
	PAD_NC(GPP_E15, NONE	),
	/* GPP_E16 - Connetced to pad 67 in M.2 NVMe slot */
	PAD_CFG_GPI(GPP_E16, NONE, DEEP),
	/* GPP_E17 - GPIO */
	PAD_NC(GPP_E17, NONE),
	/* GPP_E18 - DDP1_CTRLCLK */
	PAD_CFG_NF(GPP_E18, NONE, DEEP, NF1),
	/* GPP_E19 - DDP1_CTRLDATA */
	PAD_CFG_NF(GPP_E19, NONE, DEEP, NF1),
	/* GPP_E20 - GPIO */
	PAD_NC(GPP_E20, NATIVE),
	/* GPP_E21 - GPIO */
	PAD_NC(GPP_E21, NATIVE),
	/* GPP_E22 - DDPA_CTRLCLK */
	PAD_CFG_NF(GPP_E22, DN_20K, DEEP, NF1),
	/* GPP_E23 - DDPA_CTRLDATA */
	PAD_CFG_NF(GPP_E23, NONE, DEEP, NF1),
	/* GPP_E_CLK_LOOPBK - GPIO */
	PAD_NC(GPP_E_CLK_LOOPBK, NONE),

	/* ------- GPIO Community 5 ------- */

	/* ------- GPIO Group GPP_R ------- */

	/* GPP_R0 - HDA_BCLK */
	PAD_CFG_NF(GPP_R0, NONE, DEEP, NF1),
	/* GPP_R1 - HDA_SYNC */
	PAD_CFG_NF(GPP_R1, NATIVE, DEEP, NF1),
	/* GPP_R2 - HDA_SDO */
	PAD_CFG_NF(GPP_R2, NATIVE, DEEP, NF1),
	/* GPP_R3 - HDA_SDI0 */
	PAD_CFG_NF(GPP_R3, NATIVE, DEEP, NF1),
	/* GPP_R4 - HDA_RST# */
	PAD_CFG_NF(GPP_R4, NONE, DEEP, NF1),
	/* GPP_R5 - GPIO */
	PAD_NC(GPP_R5, NONE),
	/* GPP_R6 - GPIO */
	PAD_NC(GPP_R6, NONE),
	/* GPP_R7 - GPIO */
	PAD_NC(GPP_R7, NONE)
};

const struct pad_config *board_gpio_table(size_t *num)
{
	*num = ARRAY_SIZE(gpio_table);
	return gpio_table;
}
