/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef AMD_TURIN_POC_CPU_H
#define AMD_TURIN_POC_CPU_H

#define TURIN_A0_CPUID		CPUID_FROM_FMS(0x1a, 0x0, 0)
#define TURIN_B0_CPUID		CPUID_FROM_FMS(0x1a, 0x1, 0)
#define TURIN_B1_CPUID		CPUID_FROM_FMS(0x1a, 0x1, 1)
#define TURIN_C0_CPUID		CPUID_FROM_FMS(0x1a, 0x2, 1)
#define TURIN_C1_CPUID		CPUID_FROM_FMS(0x1a, 0x2, 1)

#endif /* AMD_TURIN_POC_CPU_H */
